"""
Django settings for EasyTesting project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import sys
import logging.handlers

# Windows 兼容：日志轮转失败时静默跳过，避免 PermissionError
if sys.platform == 'win32':
    _orig_do_rollover = logging.handlers.RotatingFileHandler.doRollover
    def _safe_do_rollover(self):
        try:
            _orig_do_rollover(self)
        except PermissionError:
            pass
    logging.handlers.RotatingFileHandler.doRollover = _safe_do_rollover

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-x&(#_g&&w!7b=3%!0ti6re^=#cwd+(s$#^$28r2s&)hhc@csy1")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() in ("1", "true", "yes")

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost,172.168.0.123").split(",")

# Application definition

INSTALLED_APPS = [
    "simpleui",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    # 'test_manager.apps.TestManagerConfig',  # 使用自定义的 AppConfig
    "django_celery_beat",

    "test_manager",

]
X_FRAME_OPTIONS = "SAMEORIGIN"
SILENCED_SYSTEM_CHECKS = ["security.W019"]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "EasyTesting.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.template.context_processors.csrf",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "test_manager.context_processors.debugtalk_functions",
            ],
        },
    },
]

WSGI_APPLICATION = "EasyTesting.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/


TIME_ZONE = "Asia/Shanghai"
LANGUAGE_CODE = "zh-hans"

USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    # 接口 JSON 响应中汉字以 UTF-8 明文输出（ensure_ascii=False），与场景执行/前置脚本日志一致
    'UNICODE_JSON': True,
    'EXCEPTION_HANDLER': 'test_manager.api.exception_handler.unified_exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'ai_generate': '10/hour',
    },
}
# 请求体大小限制（兼容大 JSON 请求体和大文件上传）
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50MB（与前端上传限制对齐）
FILE_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50MB（文件上传专用）
# 登录和登出后的重定向 URL
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/app/#/dashboard'
LOGOUT_REDIRECT_URL = '/app/#/login'
# # 邮件设置 (开发环境使用控制台输出)
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# SOCIALACCOUNT_ADAPTER = 'test_manager.social_auth_adapter.CustomSocialAccountAdapter'


# 邮件设置 - SMTP 配置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get("EMAIL_HOST", 'smtp.saferycom.com')  # SMTP 服务器地址
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 25))  # SMTP 服务器端口
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "False").lower() in ("1", "true", "yes")  # 使用 TLS 加密
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", 'hwbin@saferycom.com')  # SMTP 用户名
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", 'Qwertyu123456')  # SMTP 密码
# DEFAULT_FROM_EMAIL = '1210777805@qq.com'  # 默认发件人
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # 默认发件人

SOCIALACCOUNT_ADAPTER = 'test_manager.social_auth_adapter.CustomSocialAccountAdapter'
# simpleui 设置
SIMPLEUI_LOGO = "../static/svg/test.svg"
# 隐藏右侧SimpleUI广告链接和使用分析
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False

# 设置默认主题，指向主题css文件名。Admin Lte风格
# SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'

# 设置默认主题，指向主题css文件名。Element-ui风格
# SIMPLEUI_DEFAULT_THEME = 'element.css'

# 设置默认主题，指向主题css文件名。layui风格
SIMPLEUI_DEFAULT_THEME = 'layui.css'

# 设置默认主题，指向主题css文件名。紫色风格
# SIMPLEUI_DEFAULT_THEME = 'purple.css'


import time

SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_display': ['测试管理', '用户&设置'],  # 开启排序和过滤功能, 不填此字段为默认排序和全部显示, 空列表[] 为全部不显示.
    'dynamic': True,  # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时动态展示菜单内容
    'menus': [
        {
            'app': 'test_manager',
            'name': '测试管理',
            'icon': 'fas fa-user-shield',
            'models': [{
                'name': '项目',
                'icon': 'fa el-icon-folder',
                'url': '/admin/test_manager/project/'
            },
                {
                    'name': '环境',
                    'icon': 'fa el-icon-s-tools',
                    'url': '/admin/test_manager/environment/'
                },
                {
                    'name': '测试用例',
                    'icon': 'fa el-icon-suitcase-1',
                    'url': '/admin/test_manager/testcase/'
                },
                {
                    'name': '测试套件',
                    'icon': 'fa el-icon-suitcase',
                    'url': '/admin/test_manager/testsuite/'
                },
                {
                    'name': '测试用例分组',
                    'icon': 'fa el-icon-postcard',
                    'url': '/admin/test_manager/testcasegroup/'
                },
                {
                    'name': '测试套件分组',
                    'icon': 'fa el-icon-postcard',
                    'url': '/admin/test_manager/testsuitegroup/'
                },
                {
                    'name': '运行结果',
                    'icon': 'fa el-icon-truck',
                    'url': '/admin/test_manager/testresult/'
                },
                {
                    'name': '测试报告',
                    'icon': 'fa fa-file',
                    'url': '/admin/test_manager/testreport/'
                },

            ]
        }, {
            'name': '用户&设置',
            'icon': 'fa fa-desktop',
            'models': [{
                'name': '用户',
                'icon': 'fa fa-user',
                'url': 'auth/user/'
            },
                {
                    'name': '用户分组',
                    'icon': 'fa fa-user-group',
                    'url': 'auth/group/'
                },
                {
                    'name': '邮件配置',
                    'icon': 'fa el-icon-message',
                    'url': '/admin/test_manager/emailconfig/'
                },
            ]
        }]
}

# 在文件开头部分定义日志目录路径
LOGS_DIR = BASE_DIR / 'logs'

# 创建日志目录（如果不存在）
LOGS_DIR.mkdir(parents=True, exist_ok=True)

# 确保目录权限
os.chmod(LOGS_DIR, 0o755)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # 保留Django默认日志器
    'formatters': {
        'verbose': {  # 详细格式
            'format': '[{levelname}] {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {  # 简单格式
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        }
    },
    'handlers': {
        'console': {  # 控制台输出
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {  # 文件输出（Windows 兼容：轮转失败时静默跳过）
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'django.log',
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'mail_admins': {  # 发生错误邮件通知管理员
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler'
        },
    },
    'loggers': {
        'django': {  # Django核心日志
            'handlers': ['console', 'file', 'mail_admins'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {  # 请求相关日志
            'handlers': ['file', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'test_manager': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # 你可以自定义你的app日志
        # 'myapp': {
        #     'handlers': ['console', 'file'],
        #     'level': 'DEBUG',
        #     'propagate': False,
        # },
    },

}

# 有报错日志邮件通知
ADMINS = [
    ('胡文斌', 'hwbin@saferycom.com'),
    # 可以添加多个管理员
]
# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Shanghai'
CELERY_ENABLE_UTC = True

# Celery Beat Configuration
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# 性能压测任务调度：process=本机独立子进程（默认，无需 Celery Worker）；celery=走队列（需 Redis + Worker）
PERFORMANCE_TEST_EXECUTOR = os.environ.get("PERFORMANCE_TEST_EXECUTOR", "process").strip().lower() or "process"

# 本地敏感配置可覆盖
try:
    from .settings_local import *
except ModuleNotFoundError:
    pass