# Generated by Django 4.2.7 on 2025-04-27 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="配置名称")),
                ("is_active", models.BooleanField(default=False, verbose_name="是否激活")),
                (
                    "email_backend",
                    models.CharField(
                        choices=[
                            ("smtp", "SMTP"),
                            ("sendgrid", "SendGrid API"),
                            ("mailgun", "Mailgun API"),
                        ],
                        default="smtp",
                        max_length=20,
                        verbose_name="邮件后端",
                    ),
                ),
                (
                    "smtp_host",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="SMTP 服务器"
                    ),
                ),
                (
                    "smtp_port",
                    models.IntegerField(
                        blank=True, default=587, null=True, verbose_name="SMTP 端口"
                    ),
                ),
                (
                    "smtp_username",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="SMTP 用户名"
                    ),
                ),
                (
                    "smtp_password",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="SMTP 密码"
                    ),
                ),
                (
                    "smtp_use_tls",
                    models.BooleanField(default=True, verbose_name="使用 TLS"),
                ),
                (
                    "smtp_use_ssl",
                    models.BooleanField(default=False, verbose_name="使用 SSL"),
                ),
                (
                    "api_key",
                    models.CharField(blank=True, max_length=255, verbose_name="API 密钥"),
                ),
                (
                    "default_from_email",
                    models.EmailField(max_length=254, verbose_name="默认发件人邮箱"),
                ),
                (
                    "default_from_name",
                    models.CharField(max_length=100, verbose_name="默认发件人名称"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "邮件配置",
                "verbose_name_plural": "邮件配置",
            },
        ),
        migrations.CreateModel(
            name="Environment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("base_url", models.URLField()),
                ("variables", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "request_method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("DELETE", "DELETE"),
                            ("PATCH", "PATCH"),
                        ],
                        max_length=10,
                    ),
                ),
                ("request_url", models.CharField(max_length=500)),
                ("request_headers", models.JSONField(blank=True, default=dict)),
                ("request_body", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "request_body_format",
                    models.CharField(
                        choices=[("json", "JSON"), ("form-data", "Form Data")],
                        default="json",
                        max_length=20,
                    ),
                ),
                ("expected_status_code", models.IntegerField(default=200)),
                ("validation_rules", models.JSONField(blank=True, default=list)),
                ("extract_params", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_test_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="test_manager.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestSuite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_test_suites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_suites",
                        to="test_manager.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestSuiteCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_manager.testcase",
                    ),
                ),
                (
                    "test_suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_manager.testsuite",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="testsuite",
            name="test_cases",
            field=models.ManyToManyField(
                through="test_manager.TestSuiteCase", to="test_manager.testcase"
            ),
        ),
        migrations.CreateModel(
            name="TestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_test_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_runs",
                        to="test_manager.environment",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_runs",
                        to="test_manager.project",
                    ),
                ),
                (
                    "test_suite",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_runs",
                        to="test_manager.testsuite",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("error", "Error"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=20,
                    ),
                ),
                ("response_time", models.FloatField(blank=True, null=True)),
                ("response_status_code", models.IntegerField(blank=True, null=True)),
                ("response_headers", models.JSONField(blank=True, default=dict)),
                (
                    "response_body",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="test_manager.testcase",
                    ),
                ),
                (
                    "test_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="test_manager.testrun",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="environment",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="environments",
                to="test_manager.project",
            ),
        ),
    ]
