# Generated by Django 4.2.7 on 2025-04-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="extracted_params",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
