# Generated by Django 4.2.7 on 2025-04-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0002_testresult_extracted_params"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="validators",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
