# Generated by Django 4.2.11 on 2025-05-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0004_testresult_environment_testsuitecase_environment"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="request_body",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="testresult",
            name="request_headers",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
