# Generated by Django 4.2.11 on 2025-05-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0007_testsuiterun_testreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testreport",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
