# Generated by Django 4.2.11 on 2025-05-16 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("test_manager", "0010_testreport_test_results"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testreport",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_test_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
