# Generated by Django 4.2.11 on 2025-06-04 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("test_manager", "0011_alter_testreport_created_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="environment",
            options={"verbose_name": "环境", "verbose_name_plural": "环境"},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["name"],
                "verbose_name": "项目",
                "verbose_name_plural": "项目",
            },
        ),
        migrations.AlterModelOptions(
            name="testcase",
            options={"verbose_name": "测试用例", "verbose_name_plural": "测试用例"},
        ),
        migrations.AlterModelOptions(
            name="testcasegroup",
            options={
                "ordering": ["name"],
                "verbose_name": "用例分组",
                "verbose_name_plural": "用例分组",
            },
        ),
        migrations.AlterModelOptions(
            name="testreport",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "测试报告",
                "verbose_name_plural": "测试报告",
            },
        ),
        migrations.AlterModelOptions(
            name="testresult",
            options={"verbose_name": "测试结果", "verbose_name_plural": "测试结果"},
        ),
        migrations.AlterModelOptions(
            name="testrun",
            options={"verbose_name": "测试运行", "verbose_name_plural": "测试运行"},
        ),
        migrations.AlterModelOptions(
            name="testsuite",
            options={"verbose_name": "测试套件", "verbose_name_plural": "测试套件"},
        ),
        migrations.AlterModelOptions(
            name="testsuitegroup",
            options={
                "ordering": ["name"],
                "verbose_name": "套件分组",
                "verbose_name_plural": "套件分组",
            },
        ),
        migrations.AlterField(
            model_name="emailconfig",
            name="api_key",
            field=models.CharField(
                blank=True, db_comment="API 密钥", max_length=255, verbose_name="API 密钥"
            ),
        ),
        migrations.AlterField(
            model_name="emailconfig",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="emailconfig",
            name="default_from_email",
            field=models.EmailField(
                db_comment="默认发件人邮箱", max_length=254, verbose_name="默认发件人邮箱"
            ),
        ),
        migrations.AlterField(
            model_name="emailconfig",
            name="default_from_name",
            field=models.CharField(
                db_comment="默认发件人名称", max_length=100, verbose_name="默认发件人名称"
            ),
        ),
        migrations.AlterField(
            model_name="emailconfig",
            name="email_backend",
            field=models.CharField(
                choices=[
                    ("smtp", "SMTP"),
                    ("sendgrid", "SendGrid API"),
                    ("mailgun", "Mailgun API"),
                ],
                db_comment="邮件后端",
                default="smtp",
                max_length=20,
                verbose_name="邮件后端",
            ),
        ),
        migrations.AlterField(
            model_name="emailconfig",
            name="is_active",
            field=models.BooleanField(
                db_comment="是否激活", default=False, verbose_name="是否激活"
            ),
        ),
        migrations.AlterField(
            model_name="emailconfig",
            name="name",
            field=models.CharField(
                db_comment="配置名称", max_length=100, verbose_name="配置名称"
            ),
        ),
        migrations.AlterField(
            model_name="emailconfig",
            name="smtp_host",
            field=models.CharField(
                blank=True,
                db_comment="SMTP 服务器",
                max_length=255,
                verbose_name="SMTP 服务器",
            ),
        ),
        migrations.AlterField(
            model_name="emailconfig",
            name="smtp_password",
            field=models.CharField(
                blank=True, db_comment="SMTP 密码", max_length=255, verbose_name="SMTP 密码"
            ),
        ),
        migrations.AlterField(
            model_name="emailconfig",
            name="smtp_port",
            field=models.IntegerField(
                blank=True,
                db_comment="SMTP 端口",
                default=587,
                null=True,
                verbose_name="SMTP 端口",
            ),
        ),
        migrations.AlterField(
            model_name="emailconfig",
            name="smtp_use_ssl",
            field=models.BooleanField(
                db_comment="使用 SSL", default=False, verbose_name="使用 SSL"
            ),
        ),
        migrations.AlterField(
            model_name="emailconfig",
            name="smtp_use_tls",
            field=models.BooleanField(
                db_comment="使用 TLS", default=True, verbose_name="使用 TLS"
            ),
        ),
        migrations.AlterField(
            model_name="emailconfig",
            name="smtp_username",
            field=models.CharField(
                blank=True,
                db_comment="SMTP 用户名",
                max_length=255,
                verbose_name="SMTP 用户名",
            ),
        ),
        migrations.AlterField(
            model_name="emailconfig",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_comment="更新时间", verbose_name="更新时间"
            ),
        ),
        migrations.AlterField(
            model_name="environment",
            name="base_url",
            field=models.URLField(db_comment="环境URL", verbose_name="环境URL"),
        ),
        migrations.AlterField(
            model_name="environment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="environment",
            name="name",
            field=models.CharField(
                db_comment="环境名称", max_length=100, verbose_name="环境名称"
            ),
        ),
        migrations.AlterField(
            model_name="environment",
            name="project",
            field=models.ForeignKey(
                db_comment="所属环境",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="environments",
                to="test_manager.project",
                verbose_name="所属项目",
            ),
        ),
        migrations.AlterField(
            model_name="environment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_comment="更新时间", verbose_name="更新时间"
            ),
        ),
        migrations.AlterField(
            model_name="environment",
            name="variables",
            field=models.JSONField(
                blank=True, db_comment="环境变量", default=dict, verbose_name="环境变量"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                db_comment="创建人",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, db_comment="项目描述", verbose_name="项目描述"),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(
                db_comment="项目名称", max_length=100, verbose_name="项目名称"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_comment="更新时间", verbose_name="更新时间"
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="created_by",
            field=models.ForeignKey(
                db_comment="创建人",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_test_cases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="description",
            field=models.TextField(blank=True, db_comment="用例描述", verbose_name="用例描述"),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="expected_status_code",
            field=models.IntegerField(
                db_comment="期望状态码", default=200, verbose_name="期望状态码"
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="extract_params",
            field=models.JSONField(
                blank=True, db_comment="提取参数", default=list, verbose_name="提取参数"
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="group",
            field=models.ForeignKey(
                blank=True,
                db_comment="用例分组",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_cases",
                to="test_manager.testcasegroup",
                verbose_name="用例分组",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="name",
            field=models.CharField(
                db_comment="用例名称", max_length=100, verbose_name="用例名称"
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="project",
            field=models.ForeignKey(
                db_comment="所属项目",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_cases",
                to="test_manager.project",
                verbose_name="所属项目",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="request_body",
            field=models.JSONField(
                blank=True,
                db_comment="请求体",
                default=dict,
                null=True,
                verbose_name="请求体",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="request_body_format",
            field=models.CharField(
                choices=[("json", "JSON"), ("form-data", "Form Data")],
                db_comment="请求体格式",
                default="json",
                max_length=20,
                verbose_name="请求体格式",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="request_headers",
            field=models.JSONField(
                blank=True, db_comment="请求头", default=dict, verbose_name="请求头"
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="request_method",
            field=models.CharField(
                choices=[
                    ("GET", "GET"),
                    ("POST", "POST"),
                    ("PUT", "PUT"),
                    ("DELETE", "DELETE"),
                    ("PATCH", "PATCH"),
                ],
                db_comment="请求方法",
                max_length=10,
                verbose_name="请求方法",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="request_url",
            field=models.CharField(
                db_comment="请求URL", max_length=500, verbose_name="请求URL"
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_comment="更新时间", verbose_name="更新时间"
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="validation_rules",
            field=models.JSONField(
                blank=True, db_comment="验证规则", default=list, verbose_name="验证规则"
            ),
        ),
        migrations.AlterField(
            model_name="testcasegroup",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="testcasegroup",
            name="created_by",
            field=models.ForeignKey(
                db_comment="创建人",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_test_case_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="testcasegroup",
            name="name",
            field=models.CharField(
                db_comment="分组名称", max_length=100, verbose_name="分组名称"
            ),
        ),
        migrations.AlterField(
            model_name="testcasegroup",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_comment="父分组",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="test_manager.testcasegroup",
                verbose_name="父分组",
            ),
        ),
        migrations.AlterField(
            model_name="testcasegroup",
            name="project",
            field=models.ForeignKey(
                db_comment="所属项目",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_case_groups",
                to="test_manager.project",
                verbose_name="所属项目",
            ),
        ),
        migrations.AlterField(
            model_name="testcasegroup",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_comment="更新时间", verbose_name="更新时间"
            ),
        ),
        migrations.AlterField(
            model_name="testreport",
            name="content",
            field=models.TextField(db_comment="报告内容", verbose_name="报告内容"),
        ),
        migrations.AlterField(
            model_name="testreport",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="testreport",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_comment="创建者",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_test_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AlterField(
            model_name="testreport",
            name="description",
            field=models.TextField(
                blank=True, db_comment="报告描述", null=True, verbose_name="报告描述"
            ),
        ),
        migrations.AlterField(
            model_name="testreport",
            name="is_public",
            field=models.BooleanField(
                db_comment="公开", default=False, verbose_name="公开"
            ),
        ),
        migrations.AlterField(
            model_name="testreport",
            name="name",
            field=models.CharField(
                db_comment="报告名称", max_length=255, verbose_name="报告名称"
            ),
        ),
        migrations.AlterField(
            model_name="testreport",
            name="project",
            field=models.ForeignKey(
                db_comment="项目",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_reports",
                to="test_manager.project",
                verbose_name="项目",
            ),
        ),
        migrations.AlterField(
            model_name="testreport",
            name="report_format",
            field=models.CharField(
                choices=[("html", "HTML"), ("pdf", "PDF"), ("json", "JSON")],
                db_comment="报告格式",
                default="html",
                max_length=10,
                verbose_name="报告格式",
            ),
        ),
        migrations.AlterField(
            model_name="testreport",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("test_run", "Test Run"),
                    ("test_suite_run", "Test Suite Run"),
                    ("custom", "Custom"),
                ],
                db_comment="报告类型",
                default="test_run",
                max_length=20,
                verbose_name="报告类型",
            ),
        ),
        migrations.AlterField(
            model_name="testreport",
            name="test_results",
            field=models.ForeignKey(
                blank=True,
                db_comment="测试结果",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="test_manager.testresult",
                verbose_name="测试结果",
            ),
        ),
        migrations.AlterField(
            model_name="testreport",
            name="test_run",
            field=models.ForeignKey(
                blank=True,
                db_comment="测试运行",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="test_manager.testrun",
                verbose_name="测试运行",
            ),
        ),
        migrations.AlterField(
            model_name="testreport",
            name="test_suite_run",
            field=models.ForeignKey(
                blank=True,
                db_comment="测试套件运行",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="test_manager.testsuiterun",
                verbose_name="测试套件运行",
            ),
        ),
        migrations.AlterField(
            model_name="testreport",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_comment="更新时间", verbose_name="更新时间"
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="environment",
            field=models.ForeignKey(
                db_comment="运行环境",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_results",
                to="test_manager.environment",
                verbose_name="运行环境",
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="error_message",
            field=models.TextField(blank=True, db_comment="错误信息", verbose_name="错误信息"),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="extracted_params",
            field=models.JSONField(
                blank=True, db_comment="提取参数", default=dict, verbose_name="提取参数"
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="request_body",
            field=models.JSONField(
                blank=True,
                db_comment="请求体",
                default=dict,
                null=True,
                verbose_name="请求体",
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="request_headers",
            field=models.JSONField(
                blank=True, db_comment="请求头", default=dict, verbose_name="请求头"
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="response_body",
            field=models.JSONField(
                blank=True,
                db_comment="响应体",
                default=dict,
                null=True,
                verbose_name="响应体",
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="response_headers",
            field=models.JSONField(
                blank=True, db_comment="响应头", default=dict, verbose_name="响应头"
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="response_status_code",
            field=models.IntegerField(
                blank=True, db_comment="响应状态码", null=True, verbose_name="响应状态码"
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="response_time",
            field=models.FloatField(
                blank=True, db_comment="响应时间", null=True, verbose_name="响应时间"
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("passed", "Passed"),
                    ("failed", "Failed"),
                    ("error", "Error"),
                    ("skipped", "Skipped"),
                ],
                db_comment="运行状态",
                max_length=20,
                verbose_name="运行状态",
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_case",
            field=models.ForeignKey(
                db_comment="测试用例",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_results",
                to="test_manager.testcase",
                verbose_name="测试用例",
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test_run",
            field=models.ForeignKey(
                db_comment="测试运行",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_results",
                to="test_manager.testrun",
                verbose_name="测试运行",
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="validators",
            field=models.JSONField(
                blank=True, db_comment="验证器", default=list, verbose_name="验证器"
            ),
        ),
        migrations.AlterField(
            model_name="testrun",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="testrun",
            name="created_by",
            field=models.ForeignKey(
                db_comment="创建人",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_test_runs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="testrun",
            name="end_time",
            field=models.DateTimeField(
                blank=True, db_comment="结束时间", null=True, verbose_name="结束时间"
            ),
        ),
        migrations.AlterField(
            model_name="testrun",
            name="environment",
            field=models.ForeignKey(
                db_comment="运行环境",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_runs",
                to="test_manager.environment",
                verbose_name="运行环境",
            ),
        ),
        migrations.AlterField(
            model_name="testrun",
            name="name",
            field=models.CharField(
                db_comment="运行名称", max_length=100, verbose_name="运行名称"
            ),
        ),
        migrations.AlterField(
            model_name="testrun",
            name="project",
            field=models.ForeignKey(
                db_comment="所属项目",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_runs",
                to="test_manager.project",
                verbose_name="所属项目",
            ),
        ),
        migrations.AlterField(
            model_name="testrun",
            name="start_time",
            field=models.DateTimeField(
                blank=True, db_comment="开始时间", null=True, verbose_name="开始时间"
            ),
        ),
        migrations.AlterField(
            model_name="testrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_comment="运行状态",
                default="pending",
                max_length=20,
                verbose_name="运行状态",
            ),
        ),
        migrations.AlterField(
            model_name="testrun",
            name="test_suite",
            field=models.ForeignKey(
                blank=True,
                db_comment="测试套件",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_runs",
                to="test_manager.testsuite",
                verbose_name="测试套件",
            ),
        ),
        migrations.AlterField(
            model_name="testsuite",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="testsuite",
            name="created_by",
            field=models.ForeignKey(
                db_comment="创建人",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_test_suites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="testsuite",
            name="description",
            field=models.TextField(blank=True, db_comment="套件描述", verbose_name="套件描述"),
        ),
        migrations.AlterField(
            model_name="testsuite",
            name="group",
            field=models.ForeignKey(
                blank=True,
                db_comment="套件分组",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_suites",
                to="test_manager.testsuitegroup",
                verbose_name="套件分组",
            ),
        ),
        migrations.AlterField(
            model_name="testsuite",
            name="name",
            field=models.CharField(
                db_comment="套件名称", max_length=100, verbose_name="套件名称"
            ),
        ),
        migrations.AlterField(
            model_name="testsuite",
            name="project",
            field=models.ForeignKey(
                db_comment="所属项目",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_suites",
                to="test_manager.project",
                verbose_name="所属项目",
            ),
        ),
        migrations.AlterField(
            model_name="testsuite",
            name="test_cases",
            field=models.ManyToManyField(
                db_comment="关联用例",
                through="test_manager.TestSuiteCase",
                to="test_manager.testcase",
                verbose_name="关联用例",
            ),
        ),
        migrations.AlterField(
            model_name="testsuite",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_comment="更新时间", verbose_name="更新时间"
            ),
        ),
        migrations.AlterField(
            model_name="testsuitegroup",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="testsuitegroup",
            name="created_by",
            field=models.ForeignKey(
                db_comment="创建人",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_test_suite_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="testsuitegroup",
            name="name",
            field=models.CharField(
                db_comment="分组名称", max_length=100, verbose_name="分组名称"
            ),
        ),
        migrations.AlterField(
            model_name="testsuitegroup",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_comment="父分组",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="test_manager.testsuitegroup",
                verbose_name="父分组",
            ),
        ),
        migrations.AlterField(
            model_name="testsuitegroup",
            name="project",
            field=models.ForeignKey(
                db_comment="所属项目",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_suite_groups",
                to="test_manager.project",
                verbose_name="所属项目",
            ),
        ),
        migrations.AlterField(
            model_name="testsuitegroup",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_comment="更新时间", verbose_name="更新时间"
            ),
        ),
        migrations.CreateModel(
            name="MockData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aim",
                    models.CharField(
                        db_comment="用途", max_length=255, verbose_name="用途"
                    ),
                ),
                ("data", models.JSONField(db_comment="mock数据", verbose_name="mock数据")),
                (
                    "description",
                    models.TextField(
                        blank=True, db_comment="数据描述", verbose_name="数据描述"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_comment="创建人",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_mock_data",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "模拟数据",
                "verbose_name_plural": "模拟数据",
            },
        ),
    ]
