# Generated by Django 4.2.11 on 2025-06-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "test_manager",
            "0012_alter_environment_options_alter_project_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="mockdata",
            name="aim",
            field=models.CharField(
                db_comment="用途", default="mock数据", max_length=255, verbose_name="用途"
            ),
        ),
        migrations.AlterField(
            model_name="mockdata",
            name="data",
            field=models.TextField(db_comment="mock数据", verbose_name="mock数据"),
        ),
        migrations.AlterField(
            model_name="mockdata",
            name="description",
            field=models.TextField(
                blank=True, db_comment="数据描述", null=True, verbose_name="数据描述"
            ),
        ),
    ]
