# Generated by Django 4.2.11 on 2025-06-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0013_alter_mockdata_aim_alter_mockdata_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mockdata",
            name="aim",
            field=models.CharField(db_comment="用途", max_length=255, verbose_name="用途"),
        ),
    ]
