# Generated by Django 4.2.11 on 2025-06-11 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("test_manager", "0013_alter_mockdata_aim_alter_mockdata_data_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="任务名称", max_length=200, verbose_name="任务名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, db_comment="任务描述", verbose_name="任务描述"
                    ),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("once", "单次执行"),
                            ("daily", "每日执行"),
                            ("weekly", "每周执行"),
                            ("monthly", "每月执行"),
                            ("cron", "Cron表达式"),
                        ],
                        db_comment="调度类型",
                        default="daily",
                        max_length=20,
                        verbose_name="调度类型",
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True,
                        db_comment="Cron表达式",
                        help_text="仅当调度类型为Cron时使用",
                        max_length=100,
                        verbose_name="Cron表达式",
                    ),
                ),
                (
                    "scheduled_time",
                    models.TimeField(
                        blank=True,
                        db_comment="执行时间",
                        help_text="每日/每周/每月执行的具体时间",
                        null=True,
                        verbose_name="执行时间",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        blank=True,
                        db_comment="执行日期",
                        help_text="单次执行的日期",
                        null=True,
                        verbose_name="执行日期",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        blank=True,
                        db_comment="星期几",
                        help_text="每周执行时的星期几(1-7)",
                        null=True,
                        verbose_name="星期几",
                    ),
                ),
                (
                    "day_of_month",
                    models.IntegerField(
                        blank=True,
                        db_comment="每月第几天",
                        help_text="每月执行时的日期(1-31)",
                        null=True,
                        verbose_name="每月第几天",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "激活"),
                            ("inactive", "停用"),
                            ("paused", "暂停"),
                        ],
                        db_comment="任务状态",
                        default="active",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_comment="是否启用", default=True, verbose_name="是否启用"
                    ),
                ),
                (
                    "send_email_notification",
                    models.BooleanField(
                        db_comment="发送邮件通知", default=True, verbose_name="发送邮件通知"
                    ),
                ),
                (
                    "notification_emails",
                    models.TextField(
                        blank=True,
                        db_comment="通知邮箱",
                        help_text="多个邮箱用逗号分隔",
                        verbose_name="通知邮箱",
                    ),
                ),
                (
                    "notify_on_success",
                    models.BooleanField(
                        db_comment="成功时通知", default=False, verbose_name="成功时通知"
                    ),
                ),
                (
                    "notify_on_failure",
                    models.BooleanField(
                        db_comment="失败时通知", default=True, verbose_name="失败时通知"
                    ),
                ),
                (
                    "max_retries",
                    models.IntegerField(
                        db_comment="最大重试次数", default=3, verbose_name="最大重试次数"
                    ),
                ),
                (
                    "retry_delay",
                    models.IntegerField(
                        db_comment="重试间隔(秒)", default=300, verbose_name="重试间隔(秒)"
                    ),
                ),
                (
                    "last_run_time",
                    models.DateTimeField(
                        blank=True,
                        db_comment="上次执行时间",
                        null=True,
                        verbose_name="上次执行时间",
                    ),
                ),
                (
                    "next_run_time",
                    models.DateTimeField(
                        blank=True,
                        db_comment="下次执行时间",
                        null=True,
                        verbose_name="下次执行时间",
                    ),
                ),
                (
                    "total_runs",
                    models.IntegerField(
                        db_comment="总执行次数", default=0, verbose_name="总执行次数"
                    ),
                ),
                (
                    "successful_runs",
                    models.IntegerField(
                        db_comment="成功次数", default=0, verbose_name="成功次数"
                    ),
                ),
                (
                    "failed_runs",
                    models.IntegerField(
                        db_comment="失败次数", default=0, verbose_name="失败次数"
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        db_comment="Celery任务ID",
                        max_length=255,
                        verbose_name="Celery任务ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_comment="创建人",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_scheduled_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        db_comment="执行环境",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_tasks",
                        to="test_manager.environment",
                        verbose_name="执行环境",
                    ),
                ),
                (
                    "test_suite",
                    models.ForeignKey(
                        db_comment="测试套件",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_tasks",
                        to="test_manager.testsuite",
                        verbose_name="测试套件",
                    ),
                ),
            ],
            options={
                "verbose_name": "定时任务",
                "verbose_name_plural": "定时任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="mockdata",
            name="aim",
            field=models.CharField(db_comment="用途", max_length=255, verbose_name="用途"),
        ),
        migrations.CreateModel(
            name="TaskExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "运行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("timeout", "超时"),
                            ("cancelled", "已取消"),
                        ],
                        db_comment="执行状态",
                        default="running",
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="开始时间", verbose_name="开始时间"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, db_comment="结束时间", null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "duration",
                    models.FloatField(
                        blank=True,
                        db_comment="执行时长(秒)",
                        null=True,
                        verbose_name="执行时长(秒)",
                    ),
                ),
                (
                    "total_test_cases",
                    models.IntegerField(
                        db_comment="总测试用例数", default=0, verbose_name="总测试用例数"
                    ),
                ),
                (
                    "passed_test_cases",
                    models.IntegerField(
                        db_comment="通过用例数", default=0, verbose_name="通过用例数"
                    ),
                ),
                (
                    "failed_test_cases",
                    models.IntegerField(
                        db_comment="失败用例数", default=0, verbose_name="失败用例数"
                    ),
                ),
                (
                    "error_test_cases",
                    models.IntegerField(
                        db_comment="错误用例数", default=0, verbose_name="错误用例数"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, db_comment="错误信息", verbose_name="错误信息"
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        db_comment="重试次数", default=0, verbose_name="重试次数"
                    ),
                ),
                (
                    "email_sent",
                    models.BooleanField(
                        db_comment="邮件已发送", default=False, verbose_name="邮件已发送"
                    ),
                ),
                (
                    "email_sent_time",
                    models.DateTimeField(
                        blank=True,
                        db_comment="邮件发送时间",
                        null=True,
                        verbose_name="邮件发送时间",
                    ),
                ),
                (
                    "scheduled_task",
                    models.ForeignKey(
                        db_comment="定时任务",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_logs",
                        to="test_manager.scheduledtask",
                        verbose_name="定时任务",
                    ),
                ),
                (
                    "test_run",
                    models.ForeignKey(
                        blank=True,
                        db_comment="测试运行",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_execution_logs",
                        to="test_manager.testrun",
                        verbose_name="测试运行",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务执行日志",
                "verbose_name_plural": "任务执行日志",
                "ordering": ["-start_time"],
            },
        ),
    ]
