# Generated by Django 4.2.11 on 2025-06-11 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0014_alter_mockdata_aim"),
        ("test_manager", "0014_scheduledtask_alter_mockdata_aim_taskexecutionlog"),
    ]

    operations = []
