# Generated by Django 4.2.11 on 2025-06-13 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0015_merge_20250611_2058"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduledtask",
            name="environment",
        ),
    ]
