# Generated by Django 4.2.11 on 2025-06-13 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0016_remove_scheduledtask_environment"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledtask",
            name="environment",
            field=models.ForeignKey(
                blank=True,
                db_comment="执行环境",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduled_tasks",
                to="test_manager.environment",
                verbose_name="执行环境",
            ),
        ),
    ]
