# Generated by Django 4.2.11 on 2025-09-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0017_scheduledtask_environment"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="upload_field_name",
            field=models.CharField(
                blank=True,
                help_text="multipart/form-data 中的字段名，例如 file",
                max_length=128,
                verbose_name="文件字段名",
            ),
        ),
        migrations.AddField(
            model_name="testcase",
            name="upload_file",
            field=models.FileField(
                blank=True,
                help_text="随请求一起发送的文件",
                null=True,
                upload_to="testcase_files/%Y/%m/%d/",
                verbose_name="上传文件",
            ),
        ),
    ]
