# Generated by Django 4.2.11 on 2025-09-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0018_testcase_upload_field_name_testcase_upload_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="timeout",
            field=models.PositiveIntegerField(
                blank=True, help_text="为空时使用项目/全局默认", null=True, verbose_name="超时时间(秒)"
            ),
        ),
    ]
