# Generated by Django 4.2.11 on 2026-03-02 03:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("test_manager", "0028_apiasset_param_interaction_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apiasset",
            name="param_status",
        ),
        migrations.RemoveField(
            model_name="apiasset",
            name="param_type",
        ),
        migrations.RemoveField(
            model_name="apiasset",
            name="required",
        ),
        migrations.RemoveField(
            model_name="apiasset",
            name="sort",
        ),
    ]
