# Generated by Django 4.2.11 on 2026-03-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0036_remove_testscenedraft"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiasset",
            name="is_deleted",
            field=models.BooleanField(
                db_comment="是否删除", default=False, verbose_name="是否删除"
            ),
        ),
        migrations.AddField(
            model_name="testscene",
            name="is_deleted",
            field=models.BooleanField(
                db_comment="是否删除", default=False, verbose_name="是否删除"
            ),
        ),
        migrations.AddField(
            model_name="testscenenode",
            name="is_deleted",
            field=models.BooleanField(
                db_comment="是否删除", default=False, verbose_name="是否删除"
            ),
        ),
        migrations.AddIndex(
            model_name="testscenenode",
            index=models.Index(fields=["scene"], name="test_scene_node_scene_idx"),
        ),
        migrations.AddConstraint(
            model_name="testscenenode",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("scene", "sort"),
                name="uniq_scene_sort_active_node",
            ),
        ),
    ]
