# Generated by Django 4.2.11 on 2026-03-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0039_environment_category_global_visible_testscenenode_env"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="request_headers",
            field=models.JSONField(
                blank=True,
                db_comment="请求头预设，用于API资产编辑时一键填充",
                default=list,
                help_text="格式为 [{key, value, required, type, ...}] 的列表",
                verbose_name="请求头预设",
            ),
        ),
    ]
