# Generated by Django 4.2.11 on 2026-03-10 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("test_manager", "0040_environment_request_headers"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceTestTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="任务名称", max_length=255, verbose_name="任务名称"
                    ),
                ),
                (
                    "total_users",
                    models.IntegerField(db_comment="总虚拟用户数", verbose_name="总虚拟用户数"),
                ),
                (
                    "spawn_rate",
                    models.IntegerField(db_comment="每秒启动用户数", verbose_name="用户生成速率"),
                ),
                (
                    "run_time",
                    models.IntegerField(db_comment="压测时长（秒）", verbose_name="压测时长"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("running", "执行中"),
                            ("finished", "已完成"),
                            ("failed", "执行失败"),
                        ],
                        db_comment="任务状态",
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="执行开始时间",
                        null=True,
                        verbose_name="执行开始时间",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="执行结束时间",
                        null=True,
                        verbose_name="执行结束时间",
                    ),
                ),
                (
                    "extra_config",
                    models.JSONField(
                        blank=True,
                        db_comment="额外配置：超时时间/断言等",
                        null=True,
                        verbose_name="额外配置",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        db_comment="创建人",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        db_comment="测试环境",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_manager.environment",
                        verbose_name="测试环境",
                    ),
                ),
                (
                    "interface",
                    models.ForeignKey(
                        db_comment="关联单接口（API资产）",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_manager.apiasset",
                        verbose_name="关联单接口",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        db_comment="所属项目",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_manager.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "性能测试任务",
                "verbose_name_plural": "性能测试任务",
                "db_table": "performance_test_task",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceTestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_comment="数据时间戳", verbose_name="数据时间戳"),
                ),
                (
                    "active_users",
                    models.IntegerField(db_comment="当前活跃用户数", verbose_name="当前活跃用户数"),
                ),
                (
                    "requests_per_second",
                    models.FloatField(db_comment="每秒请求数", verbose_name="QPS"),
                ),
                (
                    "response_time_50",
                    models.FloatField(db_comment="50%响应时间（ms）", verbose_name="50%响应时间"),
                ),
                (
                    "response_time_90",
                    models.FloatField(db_comment="90%响应时间（ms）", verbose_name="90%响应时间"),
                ),
                (
                    "failure_rate",
                    models.FloatField(db_comment="失败率（%）", verbose_name="失败率"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        db_comment="所属任务",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="test_manager.performancetesttask",
                        verbose_name="所属任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "性能测试结果",
                "verbose_name_plural": "性能测试结果",
                "db_table": "performance_test_result",
                "ordering": ["task", "timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="performancetesttask",
            index=models.Index(
                fields=["project", "status"], name="perf_task_proj_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performancetesttask",
            index=models.Index(
                fields=["creator", "created_at"], name="perf_task_creator_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performancetestresult",
            index=models.Index(
                fields=["task", "timestamp"], name="perf_result_task_ts_idx"
            ),
        ),
    ]
