# Generated by Django 4.2.11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0041_performance_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsceneexecution",
            name="environment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scene_executions",
                to="test_manager.environment",
                verbose_name="运行环境",
                db_comment="运行环境",
            ),
        ),
    ]
