# Generated by Django 4.2.11 on 2026-03-13 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("test_manager", "0042_testsceneexecution_environment"),
    ]

    operations = [
        migrations.AddField(
            model_name="testscenenode",
            name="api_sync_snapshot",
            field=models.JSONField(
                blank=True, db_comment="用于回滚时恢复", default=dict, verbose_name="同步时API快照"
            ),
        ),
        migrations.AddField(
            model_name="testscenenode",
            name="api_synced_at",
            field=models.DateTimeField(
                blank=True,
                db_comment="上次从API资产同步基础信息的时间",
                null=True,
                verbose_name="API最后同步时间",
            ),
        ),
        migrations.CreateModel(
            name="TestSceneNodeSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("basic", "基础信息"),
                            ("params_add", "新增参数"),
                            ("rollback", "回滚"),
                        ],
                        db_comment="同步类型",
                        max_length=30,
                        verbose_name="同步类型",
                    ),
                ),
                (
                    "before_snapshot",
                    models.JSONField(
                        blank=True,
                        db_comment="同步前节点快照",
                        default=dict,
                        verbose_name="同步前节点快照",
                    ),
                ),
                (
                    "after_snapshot",
                    models.JSONField(
                        blank=True,
                        db_comment="同步后节点快照",
                        default=dict,
                        verbose_name="同步后节点快照",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="操作人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="node_sync_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        db_comment="场景节点",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="test_manager.testscenenode",
                        verbose_name="场景节点",
                    ),
                ),
            ],
            options={
                "verbose_name": "场景节点同步日志",
                "verbose_name_plural": "场景节点同步日志",
                "db_table": "test_scene_node_sync_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["node", "created_at"], name="node_sync_log_node_time_i"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ApiAssetChangeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("url_method", "URL/Method"),
                            ("request_params", "请求参数"),
                            ("request_body", "请求体"),
                            ("response_schema", "响应结构"),
                            ("error_code", "响应码"),
                        ],
                        db_comment="变更类型",
                        max_length=30,
                        verbose_name="变更类型",
                    ),
                ),
                (
                    "before_snapshot",
                    models.JSONField(
                        blank=True,
                        db_comment="变更前快照",
                        default=dict,
                        verbose_name="变更前快照",
                    ),
                ),
                (
                    "after_snapshot",
                    models.JSONField(
                        blank=True,
                        db_comment="变更后快照",
                        default=dict,
                        verbose_name="变更后快照",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        db_comment="接口资产",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_records",
                        to="test_manager.apiasset",
                        verbose_name="接口资产",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="操作人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_asset_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "API资产变更记录",
                "verbose_name_plural": "API资产变更记录",
                "db_table": "api_asset_change_record",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["asset", "created_at"],
                        name="api_asset_chg_asset_time_idx",
                    )
                ],
            },
        ),
    ]
