# Generated by Django 4.2.11 on 2026-03-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0043_api_asset_sync_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="testscenenodesynclog",
            name="node_snapshot_before",
            field=models.JSONField(
                blank=True,
                db_comment="同步前节点完整配置快照，回滚时优先使用",
                default=dict,
                verbose_name="同步前节点完整配置快照",
            ),
        ),
        migrations.AddField(
            model_name="testscenenodesynclog",
            name="node_snapshot_after",
            field=models.JSONField(
                blank=True,
                db_comment="同步后节点完整配置快照",
                default=dict,
                verbose_name="同步后节点完整配置快照",
            ),
        ),
    ]
