# Generated by Django 4.2.11 on 2026-03-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0044_testscenenodesynclog_node_snapshots"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiasset",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "手工"),
                    ("postman", "Postman"),
                    ("apifox", "Apifox"),
                    ("openapi", "OpenAPI"),
                    ("goreplay", "GoReplay"),
                ],
                db_comment="来源",
                default="manual",
                max_length=20,
                verbose_name="来源",
            ),
        ),
    ]
