# Generated by Django 4.2.11 on 2026-03-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0045_alter_apiasset_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="testscenenode",
            name="expected_response_body",
            field=models.JSONField(
                blank=True,
                db_comment="从回放导入的预期响应体，用于断言基线",
                default=None,
                null=True,
                verbose_name="预期响应体",
            ),
        ),
        migrations.AddField(
            model_name="testscenenode",
            name="expected_response_headers",
            field=models.JSONField(
                blank=True,
                db_comment="从回放导入的预期响应头，用于断言基线",
                default=dict,
                verbose_name="预期响应头",
            ),
        ),
    ]
