# Generated by Django 4.2.11 on 2026-03-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0046_testscenenode_expected_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="pre_request_script",
            field=models.TextField(
                blank=True,
                db_comment="JS前置脚本，为当前环境下所有接口提供统一请求预处理",
                default="",
                verbose_name="前置脚本",
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="script_timeout",
            field=models.IntegerField(
                db_comment="脚本执行超时时间，单位毫秒",
                default=1000,
                help_text="超时时间≤1000ms",
                verbose_name="脚本超时(ms)",
            ),
        ),
    ]
