# Generated by Django 4.2.11 on 2026-03-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0047_add_environment_pre_request_script"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testscenenode",
            name="on_failed",
            field=models.CharField(
                choices=[("stop", "失败终止"), ("continue", "失败继续")],
                db_comment="失败策略",
                default="continue",
                max_length=20,
                verbose_name="失败策略",
            ),
        ),
    ]
