# Generated by Django 4.2.11 on 2026-03-25 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0049_backfill_testscenenode_api_synced_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apiasset",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "API资产",
                "verbose_name_plural": "API资产",
            },
        ),
        migrations.AlterModelOptions(
            name="testscene",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "测试场景",
                "verbose_name_plural": "测试场景",
            },
        ),
    ]
