# Generated by Django 4.2.11 on 2026-03-27 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0051_testreport_scene_execution_and_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancetestresult",
            name="error_classification",
            field=models.JSONField(
                blank=True,
                db_comment="采样时刻各错误类型累计次数快照，键：http_status_error/timeout/connection_error/assertion_failure 等",
                default=dict,
                verbose_name="错误分类",
            ),
        ),
        migrations.AddField(
            model_name="performancetestresult",
            name="max_response_time",
            field=models.FloatField(
                db_comment="最大响应时间（ms），对应 Locust max_response_time",
                default=0,
                verbose_name="最大响应时间(ms)",
            ),
        ),
        migrations.AddField(
            model_name="performancetestresult",
            name="p95",
            field=models.FloatField(
                db_comment="P95 响应时间（ms），来自 Locust StatsEntry 分位数计算",
                default=0,
                verbose_name="P95 响应时间(ms)",
            ),
        ),
        migrations.AddField(
            model_name="performancetestresult",
            name="p99",
            field=models.FloatField(
                db_comment="P99 响应时间（ms）", default=0, verbose_name="P99 响应时间(ms)"
            ),
        ),
        migrations.AddField(
            model_name="performancetesttask",
            name="csv_file",
            field=models.FileField(
                blank=True,
                db_comment="CSV 参数化数据文件；列名对应占位符 {{列名}}",
                null=True,
                upload_to="performance_csv/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["csv"], message="仅支持上传 .csv 文件"
                    )
                ],
                verbose_name="CSV 参数文件",
            ),
        ),
        migrations.AlterField(
            model_name="performancetesttask",
            name="extra_config",
            field=models.JSONField(
                blank=True,
                db_comment="额外配置：timeout/assertions/stages/think_time_ms/csv_read_strategy 等",
                null=True,
                verbose_name="额外配置",
            ),
        ),
    ]
