# Generated by Django 4.2.11 on 2026-03-27 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _forward_rename_finished_to_completed(apps, schema_editor):
    Task = apps.get_model("test_manager", "PerformanceTestTask")
    Task.objects.filter(status="finished").update(status="completed")


def _reverse_rename_completed_to_finished(apps, schema_editor):
    Task = apps.get_model("test_manager", "PerformanceTestTask")
    Task.objects.filter(status="completed").update(status="finished")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("test_manager", "0052_performance_test_stage2"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancetesttask",
            name="celery_task_id",
            field=models.CharField(
                blank=True,
                db_comment="celery 模式下异步任务 id，用于 revoke",
                max_length=255,
                null=True,
                verbose_name="Celery 任务 ID",
            ),
        ),
        migrations.AddField(
            model_name="performancetesttask",
            name="runner_pid",
            field=models.IntegerField(
                blank=True,
                db_comment="process 模式下 Locust 子进程 PID，用于停止",
                null=True,
                verbose_name="执行进程 PID",
            ),
        ),
        migrations.AddField(
            model_name="performancetesttask",
            name="stop_reason",
            field=models.CharField(
                blank=True,
                db_comment="手动停止原因说明",
                default="",
                max_length=500,
                verbose_name="停止原因",
            ),
        ),
        migrations.AddField(
            model_name="performancetesttask",
            name="stopped_at",
            field=models.DateTimeField(
                blank=True, db_comment="手动停止时间", null=True, verbose_name="停止时间"
            ),
        ),
        migrations.AddField(
            model_name="performancetesttask",
            name="stopped_by",
            field=models.ForeignKey(
                blank=True,
                db_comment="手动停止操作人",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stopped_performance_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="停止人",
            ),
        ),
        migrations.RunPython(_forward_rename_finished_to_completed, _reverse_rename_completed_to_finished),
        migrations.AlterField(
            model_name="performancetesttask",
            name="finished_at",
            field=models.DateTimeField(
                blank=True,
                db_comment="执行结束时间（自然结束或手动停止）",
                null=True,
                verbose_name="执行结束时间",
            ),
        ),
        migrations.AlterField(
            model_name="performancetesttask",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("running", "执行中"),
                    ("stopped", "已停止"),
                    ("completed", "已完成"),
                    ("failed", "执行失败"),
                ],
                db_comment="任务状态",
                default="draft",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
