# Generated by Django 4.2.11 on 2026-03-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0054_performancetesttask_target_rps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performancetesttask",
            name="target_rps",
            field=models.FloatField(
                blank=True,
                db_comment="目标全局请求/秒；有值时按当前活跃用户数节流近似该 RPS，空表示不限制（由并发与思考时间决定）",
                null=True,
                verbose_name="目标 RPS",
            ),
        ),
    ]
