# Generated by Django 4.2.11 on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0057_alter_testscenenode_on_failed"),
    ]

    operations = [
        migrations.AddField(
            model_name="testscenenode",
            name="pre_request_script",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="节点前置脚本",
                db_comment="节点级前置脚本（覆盖环境和接口资产），支持 ES5.1 JavaScript",
            ),
        ),
        migrations.AddField(
            model_name="testscenenode",
            name="script_timeout",
            field=models.IntegerField(
                default=1000,
                verbose_name="脚本超时(ms)",
                db_comment="前置脚本执行超时（毫秒），0 表示使用默认值 1000ms",
            ),
        ),
    ]