# Generated by Django 4.2.11 on 2026-05-19 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("test_manager", "0058_add_testscenenode_pre_request_script"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCaseGenerationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="规则名称", max_length=100, verbose_name="规则名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, db_comment="规则描述", default="", verbose_name="规则描述"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("param_validate", "参数校验"),
                            ("biz_logic", "业务逻辑"),
                            ("error_handle", "异常处理"),
                            ("boundary", "边界值"),
                            ("security", "安全"),
                            ("performance", "性能"),
                            ("other", "其他"),
                        ],
                        db_comment="规则分类",
                        default="other",
                        max_length=20,
                        verbose_name="规则分类",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("high", "高"), ("medium", "中"), ("low", "低")],
                        db_comment="优先级",
                        default="medium",
                        max_length=10,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "rule_content",
                    models.TextField(
                        db_comment="规则内容，每行一条规则", verbose_name="规则内容（每行一条）"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_comment="是否启用", default=True, verbose_name="是否启用"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_comment="创建人",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_test_case_rules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI用例生成规则",
                "verbose_name_plural": "AI用例生成规则",
                "ordering": ["category", "-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AICaseDraftRuleUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "draft_group",
                    models.ForeignKey(
                        db_comment="草稿组",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_usages",
                        to="test_manager.aicasedraftgroup",
                        verbose_name="草稿组",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        db_comment="使用的规则",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="test_manager.testcasegenerationrule",
                        verbose_name="使用的规则",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI草稿规则使用记录",
                "verbose_name_plural": "AI草稿规则使用记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="testcasegenerationrule",
            index=models.Index(fields=["category"], name="tc_rule_category_idx"),
        ),
        migrations.AddIndex(
            model_name="testcasegenerationrule",
            index=models.Index(fields=["is_enabled"], name="tc_rule_enabled_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="aicasedraftruleusage",
            unique_together={("draft_group", "rule")},
        ),
    ]
