# Generated by Django 4.2.11 on 2026-05-19 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("test_manager", "0059_add_test_case_rule_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="模板名称", max_length=100, verbose_name="模板名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, db_comment="模板描述", verbose_name="模板描述"
                    ),
                ),
                (
                    "template_text",
                    models.TextField(db_comment="模板内容，支持变量占位符", verbose_name="模板内容"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        db_comment="是否默认模板", default=False, verbose_name="是否默认"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_comment="是否启用", default=True, verbose_name="是否启用"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_comment="创建人",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_prompt_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "提示词模板",
                "verbose_name_plural": "提示词模板",
                "ordering": ["-updated_at"],
            },
        ),
    ]
