# Generated by Django 4.2.11 on 2026-05-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0060_add_prompt_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModelProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="供应商名称", max_length=100, verbose_name="供应商名称"
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI 兼容"),
                            ("zhipu", "智谱 AI"),
                            ("deepseek", "DeepSeek"),
                            ("custom", "自定义"),
                        ],
                        db_comment="供应商类型",
                        default="openai",
                        max_length=20,
                        verbose_name="供应商类型",
                    ),
                ),
                (
                    "base_url",
                    models.CharField(
                        db_comment="API 基础地址（含协议和端口）",
                        max_length=300,
                        verbose_name="API 基础地址",
                    ),
                ),
                (
                    "api_path",
                    models.CharField(
                        db_comment="API 路径（如 /chat/completions）",
                        default="/chat/completions",
                        max_length=200,
                        verbose_name="API 路径",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        db_comment="API 密钥（Bearer Token）",
                        default="",
                        max_length=500,
                        verbose_name="API Key",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        db_comment="模型标识（如 glm-4-plus, deepseek-chat）",
                        max_length=100,
                        verbose_name="模型名称",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True,
                        db_comment="System Prompt，发送给模型的系统角色指令",
                        default="你是一个专业的API测试工程师，擅长根据接口定义生成全面的测试用例。",
                        verbose_name="系统提示词",
                    ),
                ),
                (
                    "prompt_template",
                    models.TextField(
                        db_comment="用户提示词模板，支持变量：{method} {url} {headers} {body_schema} {rules_text} {case_type} {casetype_desc}",
                        default="请根据以下接口信息和测试规则，生成{casetype_desc}类型的测试用例。\n\n【接口信息】\n请求方法：{method}\n请求URL：{url}\n请求头：{headers}\n请求体结构：{body_schema}\n\n【测试规则】\n{rules_text}\n\n【生成要求】\n1. 每个用例包含：name, request_method, request_url, request_headers, request_body, expected_status_code, validation_rules\n2. 覆盖所有规则类别\n3. 以纯 JSON 数组格式返回，不要包含任何 markdown 标记或其他文本",
                        verbose_name="提示词模板",
                    ),
                ),
                (
                    "response_cases_path",
                    models.CharField(
                        db_comment="JSON 路径，用于从响应中提取用例数组（如 choices.0.message.content）",
                        default="choices.0.message.content",
                        max_length=100,
                        verbose_name="响应用例路径",
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        db_comment="采样温度 0-2，越高越随机", default=0.7, verbose_name="温度"
                    ),
                ),
                (
                    "max_tokens",
                    models.IntegerField(
                        db_comment="单次请求最大输出 Token 数",
                        default=4096,
                        verbose_name="最大 Token",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_comment="是否启用", default=True, verbose_name="是否启用"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        db_comment="是否默认供应商", default=False, verbose_name="是否默认"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "AI大模型供应商",
                "verbose_name_plural": "AI大模型供应商",
                "db_table": "ai_model_provider",
                "ordering": ["-is_enabled", "-is_default", "name"],
            },
        ),
    ]
