# Generated by Django 4.2.11 on 2026-05-22 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("test_manager", "0061_add_ai_model_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodelprovider",
            name="prompt_template",
            field=models.TextField(
                db_comment="支持变量：{method} {url} {headers} {body_schema} {rules_text} {case_type} {casetype_desc} {api_name} {api_desc} {params} {body_format} {request_body} {response_schema} {error_codes} {auth_config}",
                default="请根据以下接口信息和测试规则，生成{casetype_desc}类型的测试用例。\n\n【接口基本信息】\n接口名称：{api_name}\n接口描述：{api_desc}\n请求方法：{method}\n请求URL：{url}\n认证方式：{auth_config}\n\n【请求参数】\nQuery/Path参数：{params}\n\n【请求体】\n类型：{body_format}\n结构：{request_body}\n\n【响应结构】\n{response_schema}\n\n【错误码】\n{error_codes}\n\n【测试规则】\n{rules_text}\n\n【生成要求】\n1. 每个用例包含：name, request_method, request_url, request_headers, request_body, expected_status_code, validation_rules\n2. 覆盖所有规则类别\n3. 以纯 JSON 数组格式返回，不要包含任何 markdown 标记或其他文本",
                verbose_name="提示词模板",
            ),
        ),
        migrations.CreateModel(
            name="AIGenerationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_prompt", models.TextField()),
                ("response_raw", models.TextField(blank=True)),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("biz_logic", "业务逻辑"),
                            ("error_handle", "异常处理"),
                            ("param_validate", "参数校验"),
                            ("performance", "性能测试"),
                            ("security", "安全测试"),
                        ],
                        default="param_validate",
                        max_length=30,
                    ),
                ),
                ("interface_info", models.JSONField(blank=True, default=dict)),
                ("case_count", models.IntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_generation_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="test_manager.aimodelprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI生成记录",
                "verbose_name_plural": "AI生成记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
