# Generated by Django 4.2.11 on 2026-05-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0062_ai_generation_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodelprovider",
            name="timeout",
            field=models.PositiveIntegerField(
                db_comment="AI 服务调用超时时间，单位秒", default=180, verbose_name="超时时间(秒)"
            ),
        ),
        migrations.AlterField(
            model_name="aigenerationrecord",
            name="case_type",
            field=models.CharField(
                choices=[
                    ("api", "接口测试"),
                    ("biz_logic", "业务逻辑"),
                    ("error_handle", "异常处理"),
                    ("param_validate", "参数校验"),
                    ("boundary", "边界值"),
                    ("performance", "性能测试"),
                    ("security", "安全测试"),
                ],
                default="param_validate",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="aimodelprovider",
            name="prompt_template",
            field=models.TextField(
                db_comment="支持变量：{method} {url} {headers} {body_schema} {rules_text} {case_type} {casetype_desc} {api_name} {api_desc} {params} {body_format} {request_body} {response_schema} {error_codes} {auth_config}",
                default='请根据以下接口信息和测试规则，生成{casetype_desc}类型的测试用例。\n\n【接口基本信息】\n接口名称：{api_name}\n接口描述：{api_desc}\n请求方法：{method}\n请求URL：{url}\n请求头：{headers}\n认证方式：{auth_config}\n\n【请求参数】\nQuery/Path参数：{params}\n\n【请求体】\n类型：{body_format}\n结构：{request_body}\n\n【响应结构】\n{response_schema}\n\n【错误码】\n{error_codes}\n\n【测试规则】\n{rules_text}\n\n【生成要求】\n1. 每个用例包含：name, request_method, request_url, request_headers, request_body, expected_status_code, validation_rules\n2. 覆盖所有规则类别\n3. validation_rules 是数组, 每项格式为：{"path": "路径", "comparator": "比较器", "expected": 期望值}；比较器可选：eq, ne, gt, ge, lt, le, contains, startswith, endswith, regex_match, length_eq\n4. request_headers 必须是 JSON 对象（字典）格式, 如 {"Content-Type": "application/json"}\n5. 以纯 JSON 数组格式返回，不要包含任何 markdown 标记或其他文本',
                verbose_name="提示词模板",
            ),
        ),
    ]
