# Generated by Django 4.2.11 on 2026-05-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0063_aimodelprovider_timeout_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aigenerationrecord",
            name="duration_ms",
            field=models.IntegerField(
                blank=True, db_comment="AI 调用耗时，单位毫秒", null=True, verbose_name="耗时(毫秒)"
            ),
        ),
    ]
