# Generated by Django 4.2.11 on 2026-05-28 07:00

from django.db import migrations, models


def _convert_request_params(apps):
    """将存量 dict 格式的 request_params 转换为结构化数组格式"""
    ApiAsset = apps.get_model("test_manager", "ApiAsset")
    updated = 0
    for asset in ApiAsset.objects.all():
        params = asset.request_params
        if not params or isinstance(params, list):
            continue
        if isinstance(params, dict):
            new_params = []
            for idx, (key, value) in enumerate(params.items()):
                key_str = str(key).strip()
                if not key_str:
                    continue
                if isinstance(value, dict) and "value" in value:
                    # 已经是半结构化格式（forms.py 写回的 format）
                    new_params.append({
                        "key": key_str,
                        "type": str(value.get("type", "string")),
                        "value": str(value.get("value", "")),
                        "required": bool(value.get("required", False)),
                        "default": str(value.get("default", "")),
                        "desc": str(value.get("description", "")),
                        "validation": "",
                    })
                else:
                    new_params.append({
                        "key": key_str,
                        "type": "string",
                        "value": str(value) if value is not None else "",
                        "required": False,
                        "default": "",
                        "desc": "",
                        "validation": "",
                    })
            asset.request_params = new_params
            asset.save(update_fields=["request_params"])
            updated += 1
    print(f"[request_params 结构化迁移] 共转换 {updated} 条记录")


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0066_aigenerationrecord_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodelprovider",
            name="api_path",
            field=models.CharField(
                blank=True,
                db_comment="API 路径（如 /chat/completions）",
                default="/chat/completions",
                max_length=200,
                verbose_name="API 路径",
            ),
        ),
        migrations.AlterField(
            model_name="apiasset",
            name="request_params",
            field=models.JSONField(
                blank=True,
                db_comment="请求参数（结构化数组：[{key,type,value,required,default,desc,validation}]）",
                default=list,
                verbose_name="请求参数",
            ),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _convert_request_params(apps),
            reverse_code=migrations.RunPython.noop,
        ),
    ]
