# Generated by Django 4.2.11 on 2026-05-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0067_request_params_structured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodelprovider",
            name="prompt_template",
            field=models.TextField(
                db_comment="支持变量：{method} {url} {headers} {body_schema} {rules_text} {case_type} {casetype_desc} {api_name} {api_desc} {param_schema} {body_format} {request_body} {response_schema} {error_codes} {auth_config}",
                default='请根据以下接口信息和测试规则，生成{casetype_desc}类型的测试用例。\n\n【接口基本信息】\n接口名称：{api_name}\n接口描述：{api_desc}\n请求方法：{method}\n请求URL：{url}\n请求头：{headers}\n认证方式：{auth_config}\n\n【请求参数Schema】\n{param_schema}\n\n【请求体】\n类型：{body_format}\n结构：{request_body}\n\n【响应结构】\n{response_schema}\n\n【错误码】\n{error_codes}\n\n【测试规则】\n{rules_text}\n\n【生成要求】\n1. 每个用例包含以下字段：name, request_method, request_url, request_headers, request_body, expected_status_code, validation_rules\n2. 覆盖所有规则类别\n3. validation_rules 是数组，每个元素格式必须为：{"path": "字段路径", "comparator": "比较器", "expected": 期望值}\n   - 注意：字段名必须使用 comparator，不要使用 validator 或其他名称\n   - 不要添加 checked 等其他多余字段\n   - 比较器可选：eq, ne, gt, ge, lt, le, contains, startswith, endswith, regex_match, length_eq\n4. request_headers 必须是 JSON 对象（字典）格式，如 {"Content-Type": "application/json"}\n5. 以纯 JSON 数组格式返回，不要包含任何 markdown 标记或其他文本\n\n输出示例：\n[\n  {\n    "name": "测试正常返回",\n    "request_method": "POST",\n    "request_url": "/api/example",\n    "request_headers": {"Content-Type": "application/json"},\n    "request_body": {"key": "value"},\n    "expected_status_code": 200,\n    "validation_rules": [\n      {"path": "$.code", "comparator": "eq", "expected": "200"},\n      {"path": "$.isSuccess", "comparator": "eq", "expected": true}\n    ]\n  }\n]',
                verbose_name="提示词模板",
            ),
        ),
    ]
