# Generated by Django 4.2.11 on 2026-06-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0068_request_params_structured_fix"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="testsceneexecution",
            index=models.Index(
                fields=["-created_at"], name="test_scene_exec_created_idx"
            ),
        ),
    ]
