# Generated by Django 4.2.11 on 2026-06-02 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("test_manager", "0069_testsceneexecution_test_scene_exec_created_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompttemplate",
            name="category",
            field=models.CharField(
                choices=[("api_gen", "API生成"), ("test_case_gen", "用例生成")],
                db_comment="模板分类：api_gen=API生成, test_case_gen=用例生成",
                default="test_case_gen",
                max_length=20,
                verbose_name="分类",
            ),
        ),
        migrations.AlterField(
            model_name="apiasset",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "手工"),
                    ("postman", "Postman"),
                    ("apifox", "Apifox"),
                    ("openapi", "OpenAPI"),
                    ("goreplay", "GoReplay"),
                    ("ai_document", "AI文档"),
                ],
                db_comment="来源",
                default="manual",
                max_length=20,
                verbose_name="来源",
            ),
        ),
        migrations.CreateModel(
            name="DocumentGenRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        db_comment="用户自定义任务名", max_length=200, verbose_name="任务名称"
                    ),
                ),
                (
                    "original_file",
                    models.FileField(
                        db_comment="上传的原始文件",
                        upload_to="document_gen/original/%Y/%m/",
                        verbose_name="原始文件",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        db_comment="原始文件名", max_length=500, verbose_name="原始文件名"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        db_comment="文件类型: docx/md", max_length=10, verbose_name="文件类型"
                    ),
                ),
                (
                    "converted_md_path",
                    models.CharField(
                        blank=True,
                        db_comment="转换后md文件相对路径",
                        max_length=500,
                        verbose_name="转换后md路径",
                    ),
                ),
                (
                    "md_content",
                    models.TextField(
                        blank=True, db_comment="md文本内容", verbose_name="Markdown内容"
                    ),
                ),
                (
                    "prompt_full_text",
                    models.TextField(
                        blank=True,
                        db_comment="实际发送给AI的完整prompt快照",
                        verbose_name="完整Prompt",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "上传中"),
                            ("converting", "转换中"),
                            ("generating", "AI生成中"),
                            ("success", "生成成功"),
                            ("failed", "生成失败"),
                        ],
                        default="uploading",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "extracted_apis",
                    models.JSONField(
                        blank=True,
                        db_comment="AI提取的API列表",
                        default=list,
                        verbose_name="提取的API列表",
                    ),
                ),
                (
                    "response_raw",
                    models.TextField(
                        blank=True, db_comment="AI原始响应内容", verbose_name="AI原始响应"
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "duration_ms",
                    models.IntegerField(blank=True, null=True, verbose_name="耗时(毫秒)"),
                ),
                (
                    "api_count",
                    models.IntegerField(
                        db_comment="提取到的API数量", default=0, verbose_name="API数量"
                    ),
                ),
                (
                    "import_status",
                    models.CharField(
                        choices=[
                            ("pending", "待导入"),
                            ("partial_imported", "部分导入"),
                            ("imported", "全部导入"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="导入状态",
                    ),
                ),
                (
                    "imported_asset_ids",
                    models.JSONField(
                        blank=True, default=list, verbose_name="已导入资产ID列表"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_gen_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "model_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="test_manager.aimodelprovider",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_gen_records",
                        to="test_manager.apiproject",
                        verbose_name="所属项目",
                    ),
                ),
                (
                    "prompt_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="test_manager.prompttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "文档AI生成记录",
                "verbose_name_plural": "文档AI生成记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
