# Generated by Django 4.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0070_document_gen_and_prompt_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentgenrecord",
            name="model_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="模型名称",
                db_comment="AI 模型名称（如 gpt-4o, deepseek-chat），创建任务时从模型供应商记录的快照",
            ),
        ),
        migrations.AddField(
            model_name="documentgenrecord",
            name="template_name",
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name="提示词模板名称",
                db_comment="提示词模板名称，创建任务时从模板记录的快照",
            ),
        ),
    ]
