# Generated by Django 4.2.11 on 2026-06-10 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0073_scheduledtask_test_scene"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskexecutionlog",
            name="scene_execution",
            field=models.ForeignKey(
                blank=True,
                db_comment="场景执行记录",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_execution_logs",
                to="test_manager.testsceneexecution",
                verbose_name="场景执行",
            ),
        ),
    ]
