# Generated by Django 4.2.11 on 2026-06-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0074_taskexecutionlog_scene_execution"),
    ]

    operations = [
        migrations.AddField(
            model_name="testscenenode",
            name="request_url",
            field=models.CharField(
                blank=True,
                db_comment="覆盖 api_asset.url，支持 {{变量}} 模板，留空则使用资产URL",
                default="",
                max_length=1024,
                verbose_name="覆盖URL路径",
            ),
        ),
    ]
