# Generated by Django 4.2.11 on 2026-06-26 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("test_manager", "0075_testscenenode_request_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="SceneDownloadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        db_comment="原始文件名", max_length=512, verbose_name="文件名"
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        db_comment="文件在存储中的相对路径", max_length=1024, verbose_name="存储路径"
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(db_comment="文件大小（字节）", verbose_name="文件大小"),
                ),
                (
                    "md5",
                    models.CharField(
                        db_comment="文件MD5校验值", max_length=32, verbose_name="文件MD5"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True,
                        db_comment="响应Content-Type",
                        default="",
                        max_length=256,
                        verbose_name="Content-Type",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="执行人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="downloaded_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        db_comment="所属执行记录",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloaded_files",
                        to="test_manager.testsceneexecution",
                        verbose_name="所属执行",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        db_comment="所属场景节点",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="downloaded_files",
                        to="test_manager.testscenenode",
                        verbose_name="所属节点",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        db_comment="所属API项目",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloaded_files",
                        to="test_manager.apiproject",
                        verbose_name="所属项目",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        db_comment="所属场景",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloaded_files",
                        to="test_manager.testscene",
                        verbose_name="所属场景",
                    ),
                ),
            ],
            options={
                "verbose_name": "下载文件",
                "verbose_name_plural": "下载文件",
                "db_table": "scene_downloaded_file",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["execution", "created_at"], name="dl_file_exec_time_idx"
                    ),
                    models.Index(
                        fields=["scene", "created_at"], name="dl_file_scene_time_idx"
                    ),
                    models.Index(
                        fields=["project", "created_at"],
                        name="dl_file_project_time_idx",
                    ),
                ],
            },
        ),
    ]
