# Generated by Django 4.2.11 on 2026-07-07 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("test_manager", "0076_scenedownloadedfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestSceneGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="分组名称", max_length=100, verbose_name="分组名称"
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(db_comment="排序", default=0, verbose_name="排序"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_comment="创建人",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_test_scene_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_comment="父分组",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="test_manager.testscenegroup",
                        verbose_name="父分组",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        db_comment="所属API项目",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_scene_groups",
                        to="test_manager.apiproject",
                        verbose_name="所属API项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "场景分组",
                "verbose_name_plural": "场景分组",
                "db_table": "test_scene_group",
                "ordering": ["sort_order", "name"],
                "unique_together": {("project", "parent", "name")},
            },
        ),
        migrations.AddField(
            model_name="testscene",
            name="group",
            field=models.ForeignKey(
                blank=True,
                db_comment="场景分组",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_scenes",
                to="test_manager.testscenegroup",
                verbose_name="场景分组",
            ),
        ),
    ]
