# Generated by Django 4.2.11 on 2026-07-07 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0077_test_scene_group_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testscene",
            name="group",
            field=models.ForeignKey(
                blank=True,
                db_comment="场景分组（复用API分组）",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_scenes",
                to="test_manager.apigroup",
                verbose_name="场景分组（复用API分组）",
            ),
        ),
        migrations.DeleteModel(
            name="TestSceneGroup",
        ),
    ]
