# Generated by Django 4.2.11 on 2026-07-11 16:04

from django.db import migrations, models


def backfill_method_from_api_asset(apps, schema_editor):
    """将已有节点关联 API 资产的 method 回填到节点自身。"""
    TestSceneNode = apps.get_model("test_manager", "TestSceneNode")
    nodes = (
        TestSceneNode.objects
        .filter(method="", api_asset__isnull=False)
        .select_related("api_asset")
    )
    for node in nodes:
        if node.api_asset and node.api_asset.method:
            node.method = node.api_asset.method
            node.save(update_fields=["method"])


def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('test_manager', '0078_alter_testscene_group_delete_testscenegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscenenode',
            name='method',
            field=models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], db_comment='节点自身的 HTTP 请求方法，创建时从关联 API 资产复制，允许独立修改', default='', max_length=10, verbose_name='请求方法'),
        ),
        migrations.RunPython(backfill_method_from_api_asset, reverse_backfill),
    ]

