# Generated by Django 4.2.30 on 2026-07-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0081_alter_apiasset_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsceneexecution",
            name="cancel_requested",
            field=models.BooleanField(
                db_comment="外部请求取消此执行，执行引擎在节点检查点读取", default=False, verbose_name="取消请求"
            ),
        ),
        migrations.AlterField(
            model_name="testsceneexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "执行中"),
                    ("success", "成功"),
                    ("failed", "失败"),
                    ("partial_success", "部分成功"),
                    ("stopped", "已停止"),
                ],
                db_comment="执行状态",
                default="running",
                max_length=20,
                verbose_name="执行状态",
            ),
        ),
    ]
