# Generated by Django 4.2.30 on 2026-08-07 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("test_manager", "0082_testsceneexecution_cancel_requested_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceBatchTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="批量任务名称", max_length=255, verbose_name="批量任务名称"
                    ),
                ),
                (
                    "execute_mode",
                    models.CharField(
                        choices=[("serial", "串行执行"), ("parallel", "并行执行")],
                        db_comment="执行模式：串行/并行",
                        default="serial",
                        max_length=20,
                        verbose_name="执行模式",
                    ),
                ),
                (
                    "max_concurrent",
                    models.IntegerField(
                        db_comment="并行执行时的最大并发数（仅并行模式有效）",
                        default=5,
                        help_text="并行模式下同时执行的任务数量上限",
                        verbose_name="最大并发数",
                    ),
                ),
                (
                    "total_tasks",
                    models.IntegerField(
                        db_comment="批量中包含的任务总数", default=0, verbose_name="总任务数"
                    ),
                ),
                (
                    "completed_tasks",
                    models.IntegerField(
                        db_comment="已完成的任务数量", default=0, verbose_name="已完成任务数"
                    ),
                ),
                (
                    "successful_tasks",
                    models.IntegerField(
                        db_comment="成功执行的任务数量", default=0, verbose_name="成功任务数"
                    ),
                ),
                (
                    "failed_tasks",
                    models.IntegerField(
                        db_comment="执行失败的任务数量", default=0, verbose_name="失败任务数"
                    ),
                ),
                (
                    "running_tasks",
                    models.IntegerField(
                        db_comment="当前正在执行的任务数量", default=0, verbose_name="运行中任务数"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("partial_success", "部分成功"),
                            ("completed", "全部完成"),
                            ("failed", "执行失败"),
                        ],
                        db_comment="批量任务状态",
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="批量任务开始执行时间",
                        null=True,
                        verbose_name="开始时间",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="批量任务全部完成时间",
                        null=True,
                        verbose_name="结束时间",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        db_comment="批量任务描述说明",
                        default="",
                        max_length=500,
                        verbose_name="描述",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        db_comment="创建人",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        db_comment="所属项目",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_manager.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "性能测试批量任务",
                "verbose_name_plural": "性能测试批量任务",
                "db_table": "performance_batch_task",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceBatchItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("skipped", "跳过"),
                        ],
                        db_comment="任务项执行状态",
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "order_index",
                    models.IntegerField(
                        db_comment="在批量中的执行顺序（串行模式有效）", default=0, verbose_name="执行顺序"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="单个任务开始执行时间",
                        null=True,
                        verbose_name="开始时间",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="单个任务执行结束时间",
                        null=True,
                        verbose_name="结束时间",
                    ),
                ),
                (
                    "error_message",
                    models.CharField(
                        blank=True,
                        db_comment="执行失败的错误信息",
                        default="",
                        max_length=500,
                        verbose_name="错误信息",
                    ),
                ),
                (
                    "result_summary",
                    models.JSONField(
                        blank=True,
                        db_comment="执行结果的概要信息（QPS、响应时间等）",
                        null=True,
                        verbose_name="结果摘要",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        db_comment="所属批量任务",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="test_manager.performancebatchtask",
                        verbose_name="所属批量任务",
                    ),
                ),
                (
                    "performance_task",
                    models.OneToOneField(
                        db_comment="关联的性能测试任务 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_manager.performancetesttask",
                        verbose_name="性能测试任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "批量任务项",
                "verbose_name_plural": "批量任务项",
                "db_table": "performance_batch_item",
                "ordering": ["batch", "order_index"],
            },
        ),
        migrations.AddIndex(
            model_name="performancebatchtask",
            index=models.Index(
                fields=["project", "status"], name="perf_batch_proj_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performancebatchtask",
            index=models.Index(
                fields=["creator", "created_at"], name="perf_batch_creator_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performancebatchtask",
            index=models.Index(
                fields=["status", "created_at"], name="perf_batch_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performancebatchitem",
            index=models.Index(
                fields=["batch", "status"], name="perf_bitem_batch_sts_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performancebatchitem",
            index=models.Index(
                fields=["batch", "order_index"], name="perf_bitem_batch_ord_idx"
            ),
        ),
    ]
