# Generated by Django 4.2.30 on 2026-08-08 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0083_performancebatchtask_performancebatchitem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performancebatchitem",
            name="performance_task",
            field=models.ForeignKey(
                db_comment="关联的性能测试任务 ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="test_manager.performancetesttask",
                verbose_name="性能测试任务",
            ),
        ),
    ]
