# Generated by Django 4.2.30 on 2026-09-04 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("test_manager", "0084_change_batch_item_to_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="SceneBatchExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="批次名称，如：批量执行 (3 个场景)",
                        max_length=200,
                        verbose_name="批次名称",
                    ),
                ),
                (
                    "execute_mode",
                    models.CharField(
                        choices=[("serial", "串行"), ("parallel", "并发")],
                        db_comment="串行/并发",
                        default="serial",
                        max_length=20,
                        verbose_name="执行方式",
                    ),
                ),
                (
                    "total_scenes",
                    models.PositiveIntegerField(
                        db_comment="场景总数", default=0, verbose_name="场景总数"
                    ),
                ),
                (
                    "completed_scenes",
                    models.PositiveIntegerField(
                        db_comment="已完成场景数", default=0, verbose_name="已完成场景数"
                    ),
                ),
                (
                    "success_scenes",
                    models.PositiveIntegerField(
                        db_comment="成功场景数", default=0, verbose_name="成功场景数"
                    ),
                ),
                (
                    "failed_scenes",
                    models.PositiveIntegerField(
                        db_comment="失败场景数", default=0, verbose_name="失败场景数"
                    ),
                ),
                (
                    "partial_scenes",
                    models.PositiveIntegerField(
                        db_comment="部分成功场景数", default=0, verbose_name="部分成功场景数"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("partial_success", "部分成功"),
                            ("stopped", "已停止"),
                        ],
                        db_comment="批次聚合状态",
                        default="running",
                        max_length=20,
                        verbose_name="批次状态",
                    ),
                ),
                (
                    "cancel_requested",
                    models.BooleanField(
                        db_comment="外部请求停止批次，调度线程在每个场景启动前读取",
                        default=False,
                        verbose_name="取消请求",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, db_comment="错误信息", default="", verbose_name="错误信息"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="开始时间", verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, db_comment="结束时间", null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="创建人",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scene_batch_executions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        blank=True,
                        db_comment="运行环境",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scene_batches",
                        to="test_manager.environment",
                        verbose_name="运行环境",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_comment="所属项目",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scene_batch_records",
                        to="test_manager.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "场景批量执行批次",
                "verbose_name_plural": "场景批量执行批次",
                "db_table": "scene_batch_execution",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="testsceneexecution",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                db_comment="批量执行时所属的批次记录",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="executions",
                to="test_manager.scenebatchexecution",
                verbose_name="所属批次",
            ),
        ),
        migrations.AddIndex(
            model_name="scenebatchexecution",
            index=models.Index(
                fields=["status", "created_at"], name="scene_batch_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scenebatchexecution",
            index=models.Index(fields=["-created_at"], name="scene_batch_created_idx"),
        ),
    ]
