# Generated by Django 4.2.30 on 2026-09-04 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0085_scenebatchexecution_testsceneexecution_batch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenebatchexecution",
            name="project",
            field=models.ForeignKey(
                blank=True,
                db_comment="所属项目（与 TestScene.project 一致，指向 ApiProject）",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scene_batch_records",
                to="test_manager.apiproject",
                verbose_name="所属项目",
            ),
        ),
    ]
