# Generated by Django 4.2.30 on 2026-09-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0086_alter_scenebatchexecution_project"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="testsceneexecution",
            index=models.Index(fields=["batch"], name="test_scene_exec_batch_idx"),
        ),
    ]
