# Generated by Django 4.2.30 on 2026-09-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0087_testsceneexecution_test_scene_exec_batch_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="testsceneexecution",
            name="test_scene_exec_batch_idx",
        ),
        migrations.AddIndex(
            model_name="testsceneexecution",
            index=models.Index(
                fields=["batch", "-created_at"], name="test_scene_exec_batch_idx"
            ),
        ),
    ]
