# Generated by Django 4.2.30 on 2026-09-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "test_manager",
            "0088_remove_testsceneexecution_test_scene_exec_batch_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="probe_url",
            field=models.CharField(
                blank=True,
                db_comment="批量执行前的 Token 探活地址；返回 401/403 时整批跳过。留空则不探活",
                default="",
                help_text="相对路径会自动拼接环境 base_url，如 /portal/system/getUserInfo",
                max_length=500,
                verbose_name="探活URL",
            ),
        ),
        migrations.AddField(
            model_name="testscenenode",
            name="retry_count",
            field=models.PositiveIntegerField(
                db_comment="节点失败后的自动重试次数，0 表示不重试", default=0, verbose_name="失败自动重试次数"
            ),
        ),
        migrations.AddField(
            model_name="testscenenode",
            name="retry_match",
            field=models.CharField(
                blank=True,
                db_comment="不为空时，失败原因或服务端 msg 包含该文本才重试（针对竞态类瞬态失败）",
                default="",
                max_length=200,
                verbose_name="重试匹配文本",
            ),
        ),
    ]
