# Generated by Django 4.2.30 on 2026-09-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "test_manager",
            "0089_environment_probe_url_testscenenode_retry_count_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledtask",
            name="test_scenes",
            field=models.ManyToManyField(
                blank=True,
                related_name="scheduled_task_batches",
                to="test_manager.testscene",
                verbose_name="测试场景列表",
            ),
        ),
    ]
