# Generated by Django 4.2.30 on 2026-09-30 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0090_scheduledtask_test_scenes"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenebatchexecution",
            name="scheduled_task",
            field=models.ForeignKey(
                blank=True,
                db_comment="定时任务触发的批次回链",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scene_batches",
                to="test_manager.scheduledtask",
                verbose_name="关联定时任务",
            ),
        ),
    ]
