# Generated by Django 4.2.11 on 2026-07-17 06:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("test_manager", "0081_alter_apiasset_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="UiActuator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="执行器名称")),
                ("host", models.CharField(max_length=200, verbose_name="主机地址")),
                ("port", models.PositiveIntegerField(default=8080, verbose_name="端口")),
                (
                    "status",
                    models.CharField(
                        choices=[("online", "在线"), ("offline", "离线")],
                        default="offline",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "browser_capabilities",
                    models.JSONField(blank=True, null=True, verbose_name="浏览器能力"),
                ),
                (
                    "last_heartbeat",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后心跳"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "UI执行器",
                "verbose_name_plural": "UI执行器",
                "db_table": "ui_actuator",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UiAICase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="用例名称")),
                ("task_description", models.TextField(verbose_name="任务描述（自然语言）")),
                ("tags", models.JSONField(blank=True, null=True, verbose_name="标签")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ui_ai_cases",
                        to="test_manager.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI AI用例",
                "verbose_name_plural": "UI AI用例",
                "db_table": "ui_ai_case",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UiBatchExecutionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="批次名称")),
                (
                    "total_cases",
                    models.PositiveIntegerField(default=0, verbose_name="总用例数"),
                ),
                (
                    "passed_cases",
                    models.PositiveIntegerField(default=0, verbose_name="通过数"),
                ),
                (
                    "failed_cases",
                    models.PositiveIntegerField(default=0, verbose_name="失败数"),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "待执行"),
                            (1, "执行中"),
                            (2, "成功"),
                            (3, "失败"),
                            (4, "部分成功"),
                        ],
                        default=0,
                        verbose_name="状态",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("manual", "手动"),
                            ("scheduled", "定时"),
                            ("api", "API触发"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="触发方式",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                ("duration", models.FloatField(default=0, verbose_name="耗时(秒)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ui_batch_records",
                        to="test_manager.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI批量执行记录",
                "verbose_name_plural": "UI批量执行记录",
                "db_table": "ui_batch_execution_record",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UiElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="元素名称")),
                (
                    "element_type",
                    models.CharField(
                        choices=[
                            ("input", "输入框"),
                            ("button", "按钮"),
                            ("link", "链接"),
                            ("dropdown", "下拉框"),
                            ("checkbox", "复选框"),
                            ("radio", "单选框"),
                            ("text", "文本"),
                            ("image", "图片"),
                            ("container", "容器"),
                            ("table", "表格"),
                            ("form", "表单"),
                            ("modal", "弹窗"),
                        ],
                        default="input",
                        max_length=20,
                        verbose_name="元素类型",
                    ),
                ),
                (
                    "locator_type",
                    models.CharField(
                        choices=[
                            ("css", "CSS Selector"),
                            ("xpath", "XPath"),
                            ("text", "Text"),
                            ("role", "Role"),
                            ("label", "Label"),
                            ("placeholder", "Placeholder"),
                            ("testid", "TestID"),
                            ("id", "ID"),
                            ("name", "Name"),
                        ],
                        max_length=20,
                        verbose_name="定位类型",
                    ),
                ),
                ("locator_value", models.CharField(max_length=500, verbose_name="定位值")),
                (
                    "locator_index",
                    models.PositiveSmallIntegerField(default=0, verbose_name="定位索引"),
                ),
                (
                    "locator_type_2",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("css", "CSS Selector"),
                            ("xpath", "XPath"),
                            ("text", "Text"),
                            ("role", "Role"),
                            ("label", "Label"),
                            ("placeholder", "Placeholder"),
                            ("testid", "TestID"),
                            ("id", "ID"),
                            ("name", "Name"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="备用定位类型2",
                    ),
                ),
                (
                    "locator_value_2",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="备用定位值2"
                    ),
                ),
                (
                    "locator_index_2",
                    models.PositiveSmallIntegerField(default=0, verbose_name="备用定位索引2"),
                ),
                (
                    "locator_type_3",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("css", "CSS Selector"),
                            ("xpath", "XPath"),
                            ("text", "Text"),
                            ("role", "Role"),
                            ("label", "Label"),
                            ("placeholder", "Placeholder"),
                            ("testid", "TestID"),
                            ("id", "ID"),
                            ("name", "Name"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="备用定位类型3",
                    ),
                ),
                (
                    "locator_value_3",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="备用定位值3"
                    ),
                ),
                (
                    "locator_index_3",
                    models.PositiveSmallIntegerField(default=0, verbose_name="备用定位索引3"),
                ),
                (
                    "is_iframe",
                    models.BooleanField(default=False, verbose_name="是否iframe内"),
                ),
                (
                    "iframe_locator",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="iframe定位器"
                    ),
                ),
                (
                    "wait_time",
                    models.PositiveSmallIntegerField(default=5, verbose_name="等待时间(秒)"),
                ),
                ("is_visible", models.BooleanField(default=True, verbose_name="是否可见")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否可用")),
                (
                    "force_action",
                    models.BooleanField(default=False, verbose_name="强制操作（忽略可见性）"),
                ),
                ("is_unique", models.BooleanField(default=False, verbose_name="是否唯一")),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("valid", "有效"),
                            ("invalid", "无效"),
                            ("unknown", "未知"),
                            ("pending", "待验证"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="验证状态",
                    ),
                ),
                (
                    "validation_message",
                    models.TextField(blank=True, default="", verbose_name="验证信息"),
                ),
                (
                    "last_validated",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后验证时间"),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(default=0, verbose_name="使用次数"),
                ),
                (
                    "component",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="组件名"
                    ),
                ),
                (
                    "page_name",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="页面标识"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI元素",
                "verbose_name_plural": "UI元素",
                "db_table": "ui_element",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UiEnvironmentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="环境名称")),
                (
                    "base_url",
                    models.URLField(blank=True, default="", verbose_name="基础URL"),
                ),
                ("is_default", models.BooleanField(default=False, verbose_name="是否默认")),
                (
                    "browser",
                    models.CharField(
                        choices=[
                            ("chromium", "Chromium"),
                            ("firefox", "Firefox"),
                            ("webkit", "WebKit"),
                        ],
                        default="chromium",
                        max_length=20,
                        verbose_name="浏览器",
                    ),
                ),
                ("headless", models.BooleanField(default=True, verbose_name="无头模式")),
                (
                    "viewport_width",
                    models.PositiveIntegerField(default=1920, verbose_name="视口宽度"),
                ),
                (
                    "viewport_height",
                    models.PositiveIntegerField(default=1080, verbose_name="视口高度"),
                ),
                (
                    "timeout",
                    models.PositiveIntegerField(default=30, verbose_name="超时(秒)"),
                ),
                ("db_status", models.BooleanField(default=False, verbose_name="启用数据库")),
                (
                    "db_type",
                    models.CharField(
                        choices=[("mysql", "MySQL"), ("db2", "DB2")],
                        default="mysql",
                        max_length=20,
                        verbose_name="数据库类型",
                    ),
                ),
                (
                    "mysql_config",
                    models.JSONField(blank=True, null=True, verbose_name="MySQL配置"),
                ),
                (
                    "db2_config",
                    models.JSONField(blank=True, null=True, verbose_name="DB2配置"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ui_environments",
                        to="test_manager.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI环境配置",
                "verbose_name_plural": "UI环境配置",
                "db_table": "ui_environment_config",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="UiModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模块名称")),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="层级",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="ui_automation.uimodule",
                        verbose_name="父模块",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ui_modules",
                        to="test_manager.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI模块",
                "verbose_name_plural": "UI模块",
                "db_table": "ui_module",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="UiPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="页面名称")),
                ("url", models.URLField(blank=True, default="", verbose_name="页面URL")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="ui_automation.uimodule",
                        verbose_name="模块",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI页面",
                "verbose_name_plural": "UI页面",
                "db_table": "ui_page",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UiPageObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="页面对象名称")),
                ("url", models.URLField(blank=True, default="", verbose_name="页面URL")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "generated_code_js",
                    models.TextField(blank=True, default="", verbose_name="生成的JS代码"),
                ),
                (
                    "generated_code_python",
                    models.TextField(
                        blank=True, default="", verbose_name="生成的Python代码"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ui_page_objects",
                        to="test_manager.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI页面对象",
                "verbose_name_plural": "UI页面对象",
                "db_table": "ui_page_object",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UiPageSteps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="步骤名称")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "flow_data",
                    models.JSONField(blank=True, null=True, verbose_name="流程图数据"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="page_steps",
                        to="ui_automation.uimodule",
                        verbose_name="模块",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="page_steps",
                        to="ui_automation.uipage",
                        verbose_name="页面",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ui_page_steps",
                        to="test_manager.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI页面步骤",
                "verbose_name_plural": "UI页面步骤",
                "db_table": "ui_page_steps",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UiTestScript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="脚本名称")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "script_type",
                    models.CharField(
                        choices=[
                            ("code", "代码"),
                            ("low_code", "低代码"),
                            ("no_code", "无代码"),
                        ],
                        default="code",
                        max_length=20,
                        verbose_name="脚本类型",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, default="", verbose_name="脚本内容"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("python", "Python"), ("javascript", "JavaScript")],
                        default="python",
                        max_length=20,
                        verbose_name="语言",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ui_scripts",
                        to="test_manager.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI测试脚本",
                "verbose_name_plural": "UI测试脚本",
                "db_table": "ui_test_script",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UiTestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="用例名称")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("P0", "P0-核心"),
                            ("P1", "P1-重要"),
                            ("P2", "P2-一般"),
                            ("P3", "P3-低"),
                        ],
                        default="P2",
                        max_length=5,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "front_sql",
                    models.TextField(blank=True, default="", verbose_name="前置SQL"),
                ),
                (
                    "front_custom",
                    models.JSONField(blank=True, null=True, verbose_name="前置自定义变量"),
                ),
                (
                    "posterior_sql",
                    models.TextField(blank=True, default="", verbose_name="后置SQL"),
                ),
                (
                    "parametrize",
                    models.JSONField(blank=True, null=True, verbose_name="参数化数据"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_cases",
                        to="ui_automation.uimodule",
                        verbose_name="模块",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ui_test_cases",
                        to="test_manager.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI测试用例",
                "verbose_name_plural": "UI测试用例",
                "db_table": "ui_test_case",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UiScriptStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_order", models.IntegerField(default=0, verbose_name="步骤序号")),
                ("action_type", models.CharField(max_length=50, verbose_name="动作类型")),
                (
                    "action_params",
                    models.JSONField(blank=True, null=True, verbose_name="动作参数"),
                ),
                (
                    "expected_result",
                    models.TextField(blank=True, default="", verbose_name="预期结果"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="ui_automation.uitestscript",
                        verbose_name="脚本",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI脚本步骤",
                "verbose_name_plural": "UI脚本步骤",
                "db_table": "ui_script_step",
                "ordering": ["step_order"],
            },
        ),
        migrations.CreateModel(
            name="UiScheduledTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="任务名称")),
                (
                    "task_type",
                    models.CharField(
                        choices=[("test_case", "测试用例"), ("test_suite", "测试套件")],
                        default="test_case",
                        max_length=20,
                        verbose_name="任务类型",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("cron", "Cron表达式"),
                            ("interval", "固定间隔"),
                            ("once", "单次执行"),
                        ],
                        default="cron",
                        max_length=20,
                        verbose_name="触发类型",
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Cron表达式"
                    ),
                ),
                (
                    "interval_seconds",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="间隔秒数"
                    ),
                ),
                (
                    "run_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="执行时间"),
                ),
                (
                    "engine",
                    models.CharField(
                        default="playwright", max_length=20, verbose_name="执行引擎"
                    ),
                ),
                (
                    "browser",
                    models.CharField(
                        choices=[
                            ("chromium", "Chromium"),
                            ("firefox", "Firefox"),
                            ("webkit", "WebKit"),
                        ],
                        default="chromium",
                        max_length=20,
                        verbose_name="浏览器",
                    ),
                ),
                ("headless", models.BooleanField(default=True, verbose_name="无头模式")),
                (
                    "notify_on_success",
                    models.BooleanField(default=False, verbose_name="成功时通知"),
                ),
                (
                    "notify_on_failure",
                    models.BooleanField(default=True, verbose_name="失败时通知"),
                ),
                (
                    "notify_email",
                    models.JSONField(blank=True, null=True, verbose_name="邮件通知配置"),
                ),
                (
                    "notify_webhook",
                    models.JSONField(blank=True, null=True, verbose_name="Webhook通知配置"),
                ),
                (
                    "total_runs",
                    models.PositiveIntegerField(default=0, verbose_name="总执行次数"),
                ),
                (
                    "successful_runs",
                    models.PositiveIntegerField(default=0, verbose_name="成功次数"),
                ),
                (
                    "failed_runs",
                    models.PositiveIntegerField(default=0, verbose_name="失败次数"),
                ),
                (
                    "last_run_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后执行时间"),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="下次执行时间"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actuator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_tasks",
                        to="ui_automation.uiactuator",
                        verbose_name="执行器",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_tasks",
                        to="ui_automation.uienvironmentconfig",
                        verbose_name="环境配置",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ui_scheduled_tasks",
                        to="test_manager.project",
                        verbose_name="项目",
                    ),
                ),
                (
                    "test_cases",
                    models.ManyToManyField(
                        blank=True,
                        related_name="scheduled_tasks",
                        to="ui_automation.uitestcase",
                        verbose_name="测试用例",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI定时任务",
                "verbose_name_plural": "UI定时任务",
                "db_table": "ui_scheduled_task",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UiPublicData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="变量名称")),
                (
                    "data_type",
                    models.SmallIntegerField(
                        choices=[(0, "字符串"), (1, "整数"), (2, "列表"), (3, "字典")],
                        default=0,
                        verbose_name="数据类型",
                    ),
                ),
                ("key", models.CharField(max_length=100, verbose_name="键名")),
                ("value", models.TextField(blank=True, default="", verbose_name="值")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ui_public_data",
                        to="test_manager.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI公共数据",
                "verbose_name_plural": "UI公共数据",
                "db_table": "ui_public_data",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UiPageStepsDetailed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step_type",
                    models.SmallIntegerField(
                        choices=[
                            (0, "元素操作"),
                            (1, "断言"),
                            (2, "SQL操作"),
                            (3, "自定义变量"),
                            (4, "条件逻辑"),
                            (5, "Python代码"),
                        ],
                        default=0,
                        verbose_name="步骤类型",
                    ),
                ),
                ("step_sort", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "ope_key",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="操作键"
                    ),
                ),
                (
                    "ope_value",
                    models.TextField(blank=True, default="", verbose_name="操作值"),
                ),
                (
                    "sql_execute",
                    models.TextField(blank=True, default="", verbose_name="SQL语句"),
                ),
                (
                    "custom",
                    models.JSONField(blank=True, null=True, verbose_name="自定义变量"),
                ),
                (
                    "condition_value",
                    models.JSONField(blank=True, null=True, verbose_name="条件值"),
                ),
                (
                    "func",
                    models.TextField(blank=True, default="", verbose_name="Python函数"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "element",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="step_details",
                        to="ui_automation.uielement",
                        verbose_name="元素",
                    ),
                ),
                (
                    "page_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="ui_automation.uipagesteps",
                        verbose_name="页面步骤",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI步骤明细",
                "verbose_name_plural": "UI步骤明细",
                "db_table": "ui_page_steps_detailed",
                "ordering": ["step_sort"],
            },
        ),
        migrations.CreateModel(
            name="UiOperationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create", "创建"),
                            ("update", "更新"),
                            ("delete", "删除"),
                            ("execute", "执行"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                ("target_model", models.CharField(max_length=50, verbose_name="目标模型")),
                ("target_id", models.PositiveIntegerField(verbose_name="目标ID")),
                (
                    "target_name",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="目标名称"
                    ),
                ),
                (
                    "old_value",
                    models.JSONField(blank=True, null=True, verbose_name="旧值"),
                ),
                (
                    "new_value",
                    models.JSONField(blank=True, null=True, verbose_name="新值"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ui_operation_records",
                        to="test_manager.project",
                        verbose_name="项目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作者",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI操作记录",
                "verbose_name_plural": "UI操作记录",
                "db_table": "ui_operation_record",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UiNotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("failure", "失败"),
                            ("error", "错误"),
                            ("timeout", "超时"),
                        ],
                        max_length=20,
                        verbose_name="触发类型",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "邮件"), ("webhook", "Webhook")],
                        max_length=20,
                        verbose_name="通知渠道",
                    ),
                ),
                ("recipient", models.CharField(max_length=200, verbose_name="接收者")),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "已发送"), ("failed", "失败"), ("retry", "重试")],
                        default="sent",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="重试次数"),
                ),
                (
                    "content",
                    models.TextField(blank=True, default="", verbose_name="通知内容"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to="ui_automation.uischeduledtask",
                        verbose_name="任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI通知日志",
                "verbose_name_plural": "UI通知日志",
                "db_table": "ui_notification_log",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="UiExecutionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "executor",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="执行者"
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "待执行"),
                            (1, "执行中"),
                            (2, "成功"),
                            (3, "失败"),
                            (4, "部分成功"),
                        ],
                        default=0,
                        verbose_name="状态",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("manual", "手动"),
                            ("scheduled", "定时"),
                            ("api", "API触发"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="触发方式",
                    ),
                ),
                (
                    "step_results",
                    models.JSONField(blank=True, null=True, verbose_name="步骤结果"),
                ),
                (
                    "screenshots",
                    models.JSONField(blank=True, null=True, verbose_name="截图列表"),
                ),
                (
                    "video_path",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="视频路径"
                    ),
                ),
                (
                    "trace_path",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="Trace路径"
                    ),
                ),
                (
                    "trace_data",
                    models.JSONField(blank=True, null=True, verbose_name="Trace数据"),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                ("duration", models.FloatField(default=0, verbose_name="耗时(秒)")),
                ("log", models.TextField(blank=True, default="", verbose_name="执行日志")),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_records",
                        to="ui_automation.uibatchexecutionrecord",
                        verbose_name="批次",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_records",
                        to="ui_automation.uitestcase",
                        verbose_name="测试用例",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI执行记录",
                "verbose_name_plural": "UI执行记录",
                "db_table": "ui_execution_record",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="UiElementGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分组名称")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="ui_automation.uielementgroup",
                        verbose_name="父分组",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ui_element_groups",
                        to="test_manager.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI元素分组",
                "verbose_name_plural": "UI元素分组",
                "db_table": "ui_element_group",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="uielement",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elements",
                to="ui_automation.uipage",
                verbose_name="页面",
            ),
        ),
        migrations.AddField(
            model_name="uielement",
            name="parent_element",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_elements",
                to="ui_automation.uielement",
                verbose_name="父元素",
            ),
        ),
        migrations.CreateModel(
            name="UiCaseStepsDetailed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_sort", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "case_data",
                    models.JSONField(blank=True, null=True, verbose_name="用例级数据覆盖"),
                ),
                (
                    "switch_step_open_url",
                    models.BooleanField(default=False, verbose_name="步骤切换时打开URL"),
                ),
                (
                    "error_retry",
                    models.PositiveSmallIntegerField(default=0, verbose_name="失败重试次数"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_references",
                        to="ui_automation.uipagesteps",
                        verbose_name="页面步骤",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_steps",
                        to="ui_automation.uitestcase",
                        verbose_name="测试用例",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI用例步骤明细",
                "verbose_name_plural": "UI用例步骤明细",
                "db_table": "ui_case_steps_detailed",
                "ordering": ["case_sort"],
            },
        ),
        migrations.CreateModel(
            name="UiAIExecutionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("passed", "通过"),
                            ("failed", "失败"),
                            ("stopped", "已停止"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "planned_tasks",
                    models.JSONField(blank=True, null=True, verbose_name="计划任务"),
                ),
                (
                    "steps_completed",
                    models.JSONField(blank=True, null=True, verbose_name="已完成步骤"),
                ),
                (
                    "screenshots_sequence",
                    models.JSONField(blank=True, null=True, verbose_name="截图序列"),
                ),
                (
                    "gif_path",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="GIF路径"
                    ),
                ),
                ("logs", models.TextField(blank=True, default="", verbose_name="执行日志")),
                ("token_cost", models.FloatField(default=0, verbose_name="Token消耗")),
                (
                    "start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                ("duration", models.FloatField(default=0, verbose_name="耗时(秒)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ai_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_records",
                        to="ui_automation.uiaicase",
                        verbose_name="AI用例",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI AI执行记录",
                "verbose_name_plural": "UI AI执行记录",
                "db_table": "ui_ai_execution_record",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UiPageObjectElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method_name", models.CharField(max_length=100, verbose_name="方法名")),
                (
                    "is_property",
                    models.BooleanField(default=True, verbose_name="是否为属性"),
                ),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="po_references",
                        to="ui_automation.uielement",
                        verbose_name="元素",
                    ),
                ),
                (
                    "page_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="po_elements",
                        to="ui_automation.uipageobject",
                        verbose_name="页面对象",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI页面对象元素",
                "verbose_name_plural": "UI页面对象元素",
                "db_table": "ui_page_object_element",
                "unique_together": {("page_object", "element")},
            },
        ),
    ]
