# Generated by Django 4.2.30 on 2026-09-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui_automation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uienvironmentconfig",
            name="auto_login",
            field=models.BooleanField(
                db_comment="执行前验证码OCR自动登录并注入token", default=False, verbose_name="自动登录"
            ),
        ),
        migrations.AddField(
            model_name="uienvironmentconfig",
            name="login_password",
            field=models.CharField(
                blank=True,
                db_comment="目标系统登录密码（内网测试账号）",
                default="",
                max_length=200,
                verbose_name="登录密码",
            ),
        ),
        migrations.AddField(
            model_name="uienvironmentconfig",
            name="login_username",
            field=models.CharField(
                blank=True,
                db_comment="目标系统登录账号",
                default="apiautotest",
                max_length=100,
                verbose_name="登录账号",
            ),
        ),
    ]
