# Generated by Django 4.2.30 on 2026-09-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui_automation", "0002_uienvironmentconfig_auto_login_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uielement",
            name="wait_time",
            field=models.PositiveSmallIntegerField(
                db_comment="定位等待时间（秒）；夜间/首次登录后页面初始化较慢，不宜过短",
                default=15,
                verbose_name="等待时间(秒)",
            ),
        ),
    ]
