# Generated by Django 4.2.30 on 2026-09-30 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ui_automation", "0003_alter_uielement_wait_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="uibatchexecutionrecord",
            name="environment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="batch_records",
                to="ui_automation.uienvironmentconfig",
                verbose_name="执行环境",
            ),
        ),
        migrations.AddField(
            model_name="uibatchexecutionrecord",
            name="scheduled_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="batches",
                to="ui_automation.uischeduledtask",
                verbose_name="关联定时任务",
            ),
        ),
    ]
